// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mq.proto

package im_mq

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushRoomMsg struct {
	Command              int32    `protobuf:"varint,1,opt,name=command,proto3" json:"command,omitempty"`
	RoomId               int64    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	UserId               int64    `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
	RemoveId             int64    `protobuf:"varint,5,opt,name=removeId,proto3" json:"removeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRoomMsg) Reset()         { *m = PushRoomMsg{} }
func (m *PushRoomMsg) String() string { return proto.CompactTextString(m) }
func (*PushRoomMsg) ProtoMessage()    {}
func (*PushRoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_7caa8199c0db1966, []int{0}
}

func (m *PushRoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRoomMsg.Unmarshal(m, b)
}
func (m *PushRoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRoomMsg.Marshal(b, m, deterministic)
}
func (m *PushRoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRoomMsg.Merge(m, src)
}
func (m *PushRoomMsg) XXX_Size() int {
	return xxx_messageInfo_PushRoomMsg.Size(m)
}
func (m *PushRoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushRoomMsg proto.InternalMessageInfo

func (m *PushRoomMsg) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *PushRoomMsg) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *PushRoomMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *PushRoomMsg) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PushRoomMsg) GetRemoveId() int64 {
	if m != nil {
		return m.RemoveId
	}
	return 0
}

func init() {
	proto.RegisterType((*PushRoomMsg)(nil), "im.mq.pushRoomMsg")
}

func init() { proto.RegisterFile("mq.proto", fileDescriptor_7caa8199c0db1966) }

var fileDescriptor_7caa8199c0db1966 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0x2d, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcc, 0xd5, 0xcb, 0x2d, 0x54, 0xea, 0x65, 0xe4, 0xe2,
	0x2e, 0x28, 0x2d, 0xce, 0x08, 0xca, 0xcf, 0xcf, 0xf5, 0x2d, 0x4e, 0x17, 0x92, 0xe0, 0x62, 0x4f,
	0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x85,
	0xc4, 0xb8, 0xd8, 0x8a, 0xf2, 0xf3, 0x73, 0x3d, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83,
	0xa0, 0x3c, 0x88, 0x8e, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x18, 0x17, 0xa4, 0xa3, 0xb4, 0x38, 0xb5, 0xc8, 0x33, 0x45, 0x82, 0x05, 0xa2, 0x03, 0xc2, 0x13,
	0x92, 0xe2, 0xe2, 0x28, 0x4a, 0xcd, 0xcd, 0x2f, 0x4b, 0xf5, 0x4c, 0x91, 0x60, 0x05, 0xcb, 0xc0,
	0xf9, 0x49, 0x6c, 0x60, 0xd7, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xda, 0x26, 0x48,
	0xa9, 0x00, 0x00, 0x00,
}
