// Code generated by protoc-gen-go. DO NOT EDIT.
// source: friend.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BecomeFriendReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BecomeFriendReq) Reset()         { *m = BecomeFriendReq{} }
func (m *BecomeFriendReq) String() string { return proto.CompactTextString(m) }
func (*BecomeFriendReq) ProtoMessage()    {}
func (*BecomeFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{0}
}

func (m *BecomeFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BecomeFriendReq.Unmarshal(m, b)
}
func (m *BecomeFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BecomeFriendReq.Marshal(b, m, deterministic)
}
func (m *BecomeFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BecomeFriendReq.Merge(m, src)
}
func (m *BecomeFriendReq) XXX_Size() int {
	return xxx_messageInfo_BecomeFriendReq.Size(m)
}
func (m *BecomeFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BecomeFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_BecomeFriendReq proto.InternalMessageInfo

func (m *BecomeFriendReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BecomeFriendReq) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type BecomeFriendRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	SecretKey            string   `protobuf:"bytes,3,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	SvcErr               int32    `protobuf:"varint,4,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BecomeFriendRsp) Reset()         { *m = BecomeFriendRsp{} }
func (m *BecomeFriendRsp) String() string { return proto.CompactTextString(m) }
func (*BecomeFriendRsp) ProtoMessage()    {}
func (*BecomeFriendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{1}
}

func (m *BecomeFriendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BecomeFriendRsp.Unmarshal(m, b)
}
func (m *BecomeFriendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BecomeFriendRsp.Marshal(b, m, deterministic)
}
func (m *BecomeFriendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BecomeFriendRsp.Merge(m, src)
}
func (m *BecomeFriendRsp) XXX_Size() int {
	return xxx_messageInfo_BecomeFriendRsp.Size(m)
}
func (m *BecomeFriendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BecomeFriendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BecomeFriendRsp proto.InternalMessageInfo

func (m *BecomeFriendRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BecomeFriendRsp) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *BecomeFriendRsp) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *BecomeFriendRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type DeleteFriendReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFriendReq) Reset()         { *m = DeleteFriendReq{} }
func (m *DeleteFriendReq) String() string { return proto.CompactTextString(m) }
func (*DeleteFriendReq) ProtoMessage()    {}
func (*DeleteFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{2}
}

func (m *DeleteFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFriendReq.Unmarshal(m, b)
}
func (m *DeleteFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFriendReq.Marshal(b, m, deterministic)
}
func (m *DeleteFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFriendReq.Merge(m, src)
}
func (m *DeleteFriendReq) XXX_Size() int {
	return xxx_messageInfo_DeleteFriendReq.Size(m)
}
func (m *DeleteFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFriendReq proto.InternalMessageInfo

func (m *DeleteFriendReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteFriendReq) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type DeleteFriendRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFriendRsp) Reset()         { *m = DeleteFriendRsp{} }
func (m *DeleteFriendRsp) String() string { return proto.CompactTextString(m) }
func (*DeleteFriendRsp) ProtoMessage()    {}
func (*DeleteFriendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{3}
}

func (m *DeleteFriendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFriendRsp.Unmarshal(m, b)
}
func (m *DeleteFriendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFriendRsp.Marshal(b, m, deterministic)
}
func (m *DeleteFriendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFriendRsp.Merge(m, src)
}
func (m *DeleteFriendRsp) XXX_Size() int {
	return xxx_messageInfo_DeleteFriendRsp.Size(m)
}
func (m *DeleteFriendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFriendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFriendRsp proto.InternalMessageInfo

func (m *DeleteFriendRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DeleteFriendRsp) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *DeleteFriendRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type BlackFriendReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlackFriendReq) Reset()         { *m = BlackFriendReq{} }
func (m *BlackFriendReq) String() string { return proto.CompactTextString(m) }
func (*BlackFriendReq) ProtoMessage()    {}
func (*BlackFriendReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{4}
}

func (m *BlackFriendReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackFriendReq.Unmarshal(m, b)
}
func (m *BlackFriendReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackFriendReq.Marshal(b, m, deterministic)
}
func (m *BlackFriendReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackFriendReq.Merge(m, src)
}
func (m *BlackFriendReq) XXX_Size() int {
	return xxx_messageInfo_BlackFriendReq.Size(m)
}
func (m *BlackFriendReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackFriendReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlackFriendReq proto.InternalMessageInfo

func (m *BlackFriendReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BlackFriendReq) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type BlackFriendRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlackFriendRsp) Reset()         { *m = BlackFriendRsp{} }
func (m *BlackFriendRsp) String() string { return proto.CompactTextString(m) }
func (*BlackFriendRsp) ProtoMessage()    {}
func (*BlackFriendRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{5}
}

func (m *BlackFriendRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlackFriendRsp.Unmarshal(m, b)
}
func (m *BlackFriendRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlackFriendRsp.Marshal(b, m, deterministic)
}
func (m *BlackFriendRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlackFriendRsp.Merge(m, src)
}
func (m *BlackFriendRsp) XXX_Size() int {
	return xxx_messageInfo_BlackFriendRsp.Size(m)
}
func (m *BlackFriendRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_BlackFriendRsp.DiscardUnknown(m)
}

var xxx_messageInfo_BlackFriendRsp proto.InternalMessageInfo

func (m *BlackFriendRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BlackFriendRsp) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *BlackFriendRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type GetFriendListReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendListReq) Reset()         { *m = GetFriendListReq{} }
func (m *GetFriendListReq) String() string { return proto.CompactTextString(m) }
func (*GetFriendListReq) ProtoMessage()    {}
func (*GetFriendListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{6}
}

func (m *GetFriendListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendListReq.Unmarshal(m, b)
}
func (m *GetFriendListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendListReq.Marshal(b, m, deterministic)
}
func (m *GetFriendListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendListReq.Merge(m, src)
}
func (m *GetFriendListReq) XXX_Size() int {
	return xxx_messageInfo_GetFriendListReq.Size(m)
}
func (m *GetFriendListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendListReq proto.InternalMessageInfo

func (m *GetFriendListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type FriendInfo struct {
	FriendId             int64    `protobuf:"varint,1,opt,name=friendId,proto3" json:"friendId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	SecretKey            string   `protobuf:"bytes,3,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendInfo) Reset()         { *m = FriendInfo{} }
func (m *FriendInfo) String() string { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()    {}
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{7}
}

func (m *FriendInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendInfo.Unmarshal(m, b)
}
func (m *FriendInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendInfo.Marshal(b, m, deterministic)
}
func (m *FriendInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendInfo.Merge(m, src)
}
func (m *FriendInfo) XXX_Size() int {
	return xxx_messageInfo_FriendInfo.Size(m)
}
func (m *FriendInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FriendInfo proto.InternalMessageInfo

func (m *FriendInfo) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *FriendInfo) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FriendInfo) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

type GetFriendListRsp struct {
	UserId               int64         `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	List                 []*FriendInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	SvcErr               int32         `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetFriendListRsp) Reset()         { *m = GetFriendListRsp{} }
func (m *GetFriendListRsp) String() string { return proto.CompactTextString(m) }
func (*GetFriendListRsp) ProtoMessage()    {}
func (*GetFriendListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{8}
}

func (m *GetFriendListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendListRsp.Unmarshal(m, b)
}
func (m *GetFriendListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendListRsp.Marshal(b, m, deterministic)
}
func (m *GetFriendListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendListRsp.Merge(m, src)
}
func (m *GetFriendListRsp) XXX_Size() int {
	return xxx_messageInfo_GetFriendListRsp.Size(m)
}
func (m *GetFriendListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendListRsp proto.InternalMessageInfo

func (m *GetFriendListRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetFriendListRsp) GetList() []*FriendInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetFriendListRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type GetFriendInfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=FriendId,proto3" json:"FriendId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendInfoReq) Reset()         { *m = GetFriendInfoReq{} }
func (m *GetFriendInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetFriendInfoReq) ProtoMessage()    {}
func (*GetFriendInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{9}
}

func (m *GetFriendInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendInfoReq.Unmarshal(m, b)
}
func (m *GetFriendInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendInfoReq.Marshal(b, m, deterministic)
}
func (m *GetFriendInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendInfoReq.Merge(m, src)
}
func (m *GetFriendInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetFriendInfoReq.Size(m)
}
func (m *GetFriendInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendInfoReq proto.InternalMessageInfo

func (m *GetFriendInfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetFriendInfoReq) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

type GetFriendInfoRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	FriendId             int64    `protobuf:"varint,2,opt,name=friendId,proto3" json:"friendId,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	SecretKey            string   `protobuf:"bytes,4,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	SvcErr               int32    `protobuf:"varint,5,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFriendInfoRsp) Reset()         { *m = GetFriendInfoRsp{} }
func (m *GetFriendInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetFriendInfoRsp) ProtoMessage()    {}
func (*GetFriendInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b65cbc293af6bbd, []int{10}
}

func (m *GetFriendInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFriendInfoRsp.Unmarshal(m, b)
}
func (m *GetFriendInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFriendInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetFriendInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFriendInfoRsp.Merge(m, src)
}
func (m *GetFriendInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetFriendInfoRsp.Size(m)
}
func (m *GetFriendInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFriendInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetFriendInfoRsp proto.InternalMessageInfo

func (m *GetFriendInfoRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetFriendInfoRsp) GetFriendId() int64 {
	if m != nil {
		return m.FriendId
	}
	return 0
}

func (m *GetFriendInfoRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetFriendInfoRsp) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *GetFriendInfoRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

func init() {
	proto.RegisterType((*BecomeFriendReq)(nil), "inner.BecomeFriendReq")
	proto.RegisterType((*BecomeFriendRsp)(nil), "inner.BecomeFriendRsp")
	proto.RegisterType((*DeleteFriendReq)(nil), "inner.DeleteFriendReq")
	proto.RegisterType((*DeleteFriendRsp)(nil), "inner.DeleteFriendRsp")
	proto.RegisterType((*BlackFriendReq)(nil), "inner.BlackFriendReq")
	proto.RegisterType((*BlackFriendRsp)(nil), "inner.BlackFriendRsp")
	proto.RegisterType((*GetFriendListReq)(nil), "inner.GetFriendListReq")
	proto.RegisterType((*FriendInfo)(nil), "inner.FriendInfo")
	proto.RegisterType((*GetFriendListRsp)(nil), "inner.GetFriendListRsp")
	proto.RegisterType((*GetFriendInfoReq)(nil), "inner.GetFriendInfoReq")
	proto.RegisterType((*GetFriendInfoRsp)(nil), "inner.GetFriendInfoRsp")
}

func init() { proto.RegisterFile("friend.proto", fileDescriptor_2b65cbc293af6bbd) }

var fileDescriptor_2b65cbc293af6bbd = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x25, 0x4d, 0x5b, 0xec, 0xb4, 0x7e, 0x2d, 0x58, 0x43, 0xf0, 0x10, 0x02, 0x42, 0xf0, 0xd0,
	0x43, 0x3d, 0x0a, 0x42, 0x4b, 0x5b, 0x29, 0x7a, 0xca, 0x59, 0x85, 0x9a, 0x4e, 0x20, 0x58, 0x93,
	0x75, 0x77, 0x2b, 0x88, 0x7f, 0xc3, 0xdf, 0xe5, 0x6f, 0x92, 0x6c, 0xd2, 0x36, 0x59, 0xb7, 0x39,
	0xb4, 0x1e, 0xe7, 0x63, 0xdf, 0xbc, 0xb7, 0xfb, 0x66, 0xa1, 0x13, 0xb2, 0x08, 0xe3, 0x79, 0x8f,
	0xb2, 0x44, 0x24, 0xa4, 0x11, 0xc5, 0x31, 0x32, 0x77, 0x0c, 0xc7, 0x43, 0x0c, 0x92, 0x37, 0x9c,
	0xc8, 0xa2, 0x8f, 0xef, 0xa4, 0x0b, 0xcd, 0x25, 0x47, 0x36, 0x9d, 0x5b, 0x86, 0x63, 0x78, 0xa6,
	0x9f, 0x47, 0xc4, 0x86, 0x83, 0xac, 0x69, 0x3a, 0xb7, 0x6a, 0xb2, 0xb2, 0x8e, 0xdd, 0x2f, 0x05,
	0x86, 0xd3, 0x5d, 0x60, 0xc8, 0x05, 0xb4, 0x38, 0x06, 0x0c, 0xc5, 0x3d, 0x7e, 0x5a, 0xa6, 0x63,
	0x78, 0x2d, 0x7f, 0x93, 0x48, 0x11, 0xf9, 0x47, 0x30, 0x66, 0xcc, 0xaa, 0x3b, 0x86, 0xd7, 0xf0,
	0xf3, 0x28, 0xd5, 0x30, 0xc2, 0x05, 0x8a, 0x3d, 0x35, 0x3c, 0x29, 0x30, 0x3b, 0x6a, 0xd8, 0xb0,
	0x34, 0x4b, 0x2c, 0x47, 0x70, 0x34, 0x5c, 0xcc, 0x82, 0xd7, 0xfd, 0x48, 0x3e, 0x96, 0x51, 0xfe,
	0x99, 0xe3, 0x15, 0x9c, 0xdc, 0xa1, 0xc8, 0xda, 0x1e, 0x22, 0x2e, 0x2a, 0x58, 0xba, 0xcf, 0x00,
	0x39, 0x5e, 0x1c, 0x26, 0xe9, 0xb4, 0x70, 0x35, 0x2d, 0xeb, 0x5b, 0xc7, 0x72, 0x9a, 0x98, 0x89,
	0x25, 0x97, 0x3c, 0xd2, 0x69, 0x32, 0xaa, 0x7e, 0x6d, 0x37, 0x52, 0xb9, 0x54, 0x68, 0xbd, 0x84,
	0xfa, 0x22, 0xe2, 0xc2, 0xaa, 0x39, 0xa6, 0xd7, 0xee, 0x9f, 0xf6, 0xa4, 0xb7, 0x7b, 0x1b, 0x7a,
	0xbe, 0x2c, 0x6f, 0x95, 0x3d, 0x29, 0x8c, 0x92, 0xed, 0x3b, 0x3e, 0xce, 0xb7, 0xa1, 0x02, 0x55,
	0xbf, 0x4f, 0xa8, 0x00, 0x69, 0x6e, 0xcc, 0xdc, 0x7e, 0x63, 0xf5, 0xed, 0xfb, 0xd1, 0x28, 0xca,
	0xeb, 0xff, 0xd4, 0xa0, 0x35, 0xa0, 0x51, 0x46, 0x8b, 0xdc, 0x42, 0xa7, 0xb8, 0xaa, 0xa4, 0x9b,
	0xdf, 0x96, 0xf2, 0x0d, 0xd8, 0xda, 0x3c, 0xa7, 0xe9, 0xf9, 0xe2, 0x9a, 0xac, 0xcf, 0x2b, 0x2b,
	0x68, 0x6b, 0xf3, 0x9c, 0x92, 0x1b, 0x68, 0x17, 0x1c, 0x4c, 0xce, 0x56, 0x63, 0x4a, 0xbb, 0x61,
	0xeb, 0xd2, 0x9c, 0x92, 0x01, 0x1c, 0x96, 0x4c, 0x41, 0xce, 0xf3, 0x3e, 0xd5, 0xb6, 0xb6, 0xbe,
	0xa0, 0x40, 0x48, 0xeb, 0xfe, 0xe9, 0xcc, 0x2d, 0x60, 0xeb, 0x0b, 0x9c, 0xbe, 0x34, 0xe5, 0x17,
	0x7a, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x17, 0xf9, 0x5a, 0xd9, 0x52, 0x05, 0x00, 0x00,
}
