// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: group.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ApiUser service

func NewApiUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ApiUser service

type ApiUserService interface {
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...client.CallOption) (*CreateGroupRsp, error)
	DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...client.CallOption) (*DismissGroupRsp, error)
	ChangeGroupMaster(ctx context.Context, in *ChangeGroupMasterReq, opts ...client.CallOption) (*ChangeGroupMasterRsp, error)
	AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...client.CallOption) (*AddGroupMemberRsp, error)
	RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...client.CallOption) (*RemoveGroupMemberRsp, error)
	QuitGroupMember(ctx context.Context, in *QuitGroupMemberReq, opts ...client.CallOption) (*QuitGroupMemberRsp, error)
	GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...client.CallOption) (*GetGroupInfoRsp, error)
	GetGroupList(ctx context.Context, in *GetGroupListReq, opts ...client.CallOption) (*GetGroupListRsp, error)
}

type apiUserService struct {
	c    client.Client
	name string
}

func NewApiUserService(name string, c client.Client) ApiUserService {
	return &apiUserService{
		c:    c,
		name: name,
	}
}

func (c *apiUserService) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...client.CallOption) (*CreateGroupRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.CreateGroup", in)
	out := new(CreateGroupRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) DismissGroup(ctx context.Context, in *DismissGroupReq, opts ...client.CallOption) (*DismissGroupRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.DismissGroup", in)
	out := new(DismissGroupRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) ChangeGroupMaster(ctx context.Context, in *ChangeGroupMasterReq, opts ...client.CallOption) (*ChangeGroupMasterRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.ChangeGroupMaster", in)
	out := new(ChangeGroupMasterRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...client.CallOption) (*AddGroupMemberRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.AddGroupMember", in)
	out := new(AddGroupMemberRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...client.CallOption) (*RemoveGroupMemberRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.RemoveGroupMember", in)
	out := new(RemoveGroupMemberRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) QuitGroupMember(ctx context.Context, in *QuitGroupMemberReq, opts ...client.CallOption) (*QuitGroupMemberRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.QuitGroupMember", in)
	out := new(QuitGroupMemberRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...client.CallOption) (*GetGroupInfoRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.GetGroupInfo", in)
	out := new(GetGroupInfoRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) GetGroupList(ctx context.Context, in *GetGroupListReq, opts ...client.CallOption) (*GetGroupListRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.GetGroupList", in)
	out := new(GetGroupListRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiUser service

type ApiUserHandler interface {
	CreateGroup(context.Context, *CreateGroupReq, *CreateGroupRsp) error
	DismissGroup(context.Context, *DismissGroupReq, *DismissGroupRsp) error
	ChangeGroupMaster(context.Context, *ChangeGroupMasterReq, *ChangeGroupMasterRsp) error
	AddGroupMember(context.Context, *AddGroupMemberReq, *AddGroupMemberRsp) error
	RemoveGroupMember(context.Context, *RemoveGroupMemberReq, *RemoveGroupMemberRsp) error
	QuitGroupMember(context.Context, *QuitGroupMemberReq, *QuitGroupMemberRsp) error
	GetGroupInfo(context.Context, *GetGroupInfoReq, *GetGroupInfoRsp) error
	GetGroupList(context.Context, *GetGroupListReq, *GetGroupListRsp) error
}

func RegisterApiUserHandler(s server.Server, hdlr ApiUserHandler, opts ...server.HandlerOption) error {
	type apiUser interface {
		CreateGroup(ctx context.Context, in *CreateGroupReq, out *CreateGroupRsp) error
		DismissGroup(ctx context.Context, in *DismissGroupReq, out *DismissGroupRsp) error
		ChangeGroupMaster(ctx context.Context, in *ChangeGroupMasterReq, out *ChangeGroupMasterRsp) error
		AddGroupMember(ctx context.Context, in *AddGroupMemberReq, out *AddGroupMemberRsp) error
		RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, out *RemoveGroupMemberRsp) error
		QuitGroupMember(ctx context.Context, in *QuitGroupMemberReq, out *QuitGroupMemberRsp) error
		GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, out *GetGroupInfoRsp) error
		GetGroupList(ctx context.Context, in *GetGroupListReq, out *GetGroupListRsp) error
	}
	type ApiUser struct {
		apiUser
	}
	h := &apiUserHandler{hdlr}
	return s.Handle(s.NewHandler(&ApiUser{h}, opts...))
}

type apiUserHandler struct {
	ApiUserHandler
}

func (h *apiUserHandler) CreateGroup(ctx context.Context, in *CreateGroupReq, out *CreateGroupRsp) error {
	return h.ApiUserHandler.CreateGroup(ctx, in, out)
}

func (h *apiUserHandler) DismissGroup(ctx context.Context, in *DismissGroupReq, out *DismissGroupRsp) error {
	return h.ApiUserHandler.DismissGroup(ctx, in, out)
}

func (h *apiUserHandler) ChangeGroupMaster(ctx context.Context, in *ChangeGroupMasterReq, out *ChangeGroupMasterRsp) error {
	return h.ApiUserHandler.ChangeGroupMaster(ctx, in, out)
}

func (h *apiUserHandler) AddGroupMember(ctx context.Context, in *AddGroupMemberReq, out *AddGroupMemberRsp) error {
	return h.ApiUserHandler.AddGroupMember(ctx, in, out)
}

func (h *apiUserHandler) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, out *RemoveGroupMemberRsp) error {
	return h.ApiUserHandler.RemoveGroupMember(ctx, in, out)
}

func (h *apiUserHandler) QuitGroupMember(ctx context.Context, in *QuitGroupMemberReq, out *QuitGroupMemberRsp) error {
	return h.ApiUserHandler.QuitGroupMember(ctx, in, out)
}

func (h *apiUserHandler) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, out *GetGroupInfoRsp) error {
	return h.ApiUserHandler.GetGroupInfo(ctx, in, out)
}

func (h *apiUserHandler) GetGroupList(ctx context.Context, in *GetGroupListReq, out *GetGroupListRsp) error {
	return h.ApiUserHandler.GetGroupList(ctx, in, out)
}
