// Code generated by protoc-gen-go. DO NOT EDIT.
// source: group.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGroupReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupType            int32    `protobuf:"varint,2,opt,name=groupType,proto3" json:"groupType,omitempty"`
	Mute                 int32    `protobuf:"varint,3,opt,name=mute,proto3" json:"mute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupReq) Reset()         { *m = CreateGroupReq{} }
func (m *CreateGroupReq) String() string { return proto.CompactTextString(m) }
func (*CreateGroupReq) ProtoMessage()    {}
func (*CreateGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{0}
}

func (m *CreateGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupReq.Unmarshal(m, b)
}
func (m *CreateGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupReq.Marshal(b, m, deterministic)
}
func (m *CreateGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupReq.Merge(m, src)
}
func (m *CreateGroupReq) XXX_Size() int {
	return xxx_messageInfo_CreateGroupReq.Size(m)
}
func (m *CreateGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupReq proto.InternalMessageInfo

func (m *CreateGroupReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateGroupReq) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *CreateGroupReq) GetMute() int32 {
	if m != nil {
		return m.Mute
	}
	return 0
}

type CreateGroupRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	GroupType            int32    `protobuf:"varint,4,opt,name=groupType,proto3" json:"groupType,omitempty"`
	Mute                 int32    `protobuf:"varint,5,opt,name=mute,proto3" json:"mute,omitempty"`
	Master               int64    `protobuf:"varint,6,opt,name=master,proto3" json:"master,omitempty"`
	SecretKey            string   `protobuf:"bytes,7,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	SvcErr               int32    `protobuf:"varint,8,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRsp) Reset()         { *m = CreateGroupRsp{} }
func (m *CreateGroupRsp) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRsp) ProtoMessage()    {}
func (*CreateGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{1}
}

func (m *CreateGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRsp.Unmarshal(m, b)
}
func (m *CreateGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRsp.Marshal(b, m, deterministic)
}
func (m *CreateGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRsp.Merge(m, src)
}
func (m *CreateGroupRsp) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRsp.Size(m)
}
func (m *CreateGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRsp proto.InternalMessageInfo

func (m *CreateGroupRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateGroupRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *CreateGroupRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CreateGroupRsp) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *CreateGroupRsp) GetMute() int32 {
	if m != nil {
		return m.Mute
	}
	return 0
}

func (m *CreateGroupRsp) GetMaster() int64 {
	if m != nil {
		return m.Master
	}
	return 0
}

func (m *CreateGroupRsp) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *CreateGroupRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type DismissGroupReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DismissGroupReq) Reset()         { *m = DismissGroupReq{} }
func (m *DismissGroupReq) String() string { return proto.CompactTextString(m) }
func (*DismissGroupReq) ProtoMessage()    {}
func (*DismissGroupReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{2}
}

func (m *DismissGroupReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DismissGroupReq.Unmarshal(m, b)
}
func (m *DismissGroupReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DismissGroupReq.Marshal(b, m, deterministic)
}
func (m *DismissGroupReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DismissGroupReq.Merge(m, src)
}
func (m *DismissGroupReq) XXX_Size() int {
	return xxx_messageInfo_DismissGroupReq.Size(m)
}
func (m *DismissGroupReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DismissGroupReq.DiscardUnknown(m)
}

var xxx_messageInfo_DismissGroupReq proto.InternalMessageInfo

func (m *DismissGroupReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DismissGroupReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type DismissGroupRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DismissGroupRsp) Reset()         { *m = DismissGroupRsp{} }
func (m *DismissGroupRsp) String() string { return proto.CompactTextString(m) }
func (*DismissGroupRsp) ProtoMessage()    {}
func (*DismissGroupRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{3}
}

func (m *DismissGroupRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DismissGroupRsp.Unmarshal(m, b)
}
func (m *DismissGroupRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DismissGroupRsp.Marshal(b, m, deterministic)
}
func (m *DismissGroupRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DismissGroupRsp.Merge(m, src)
}
func (m *DismissGroupRsp) XXX_Size() int {
	return xxx_messageInfo_DismissGroupRsp.Size(m)
}
func (m *DismissGroupRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DismissGroupRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DismissGroupRsp proto.InternalMessageInfo

func (m *DismissGroupRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *DismissGroupRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *DismissGroupRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type ChangeGroupMasterReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	NewMaster            int64    `protobuf:"varint,3,opt,name=newMaster,proto3" json:"newMaster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeGroupMasterReq) Reset()         { *m = ChangeGroupMasterReq{} }
func (m *ChangeGroupMasterReq) String() string { return proto.CompactTextString(m) }
func (*ChangeGroupMasterReq) ProtoMessage()    {}
func (*ChangeGroupMasterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{4}
}

func (m *ChangeGroupMasterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGroupMasterReq.Unmarshal(m, b)
}
func (m *ChangeGroupMasterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGroupMasterReq.Marshal(b, m, deterministic)
}
func (m *ChangeGroupMasterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGroupMasterReq.Merge(m, src)
}
func (m *ChangeGroupMasterReq) XXX_Size() int {
	return xxx_messageInfo_ChangeGroupMasterReq.Size(m)
}
func (m *ChangeGroupMasterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGroupMasterReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGroupMasterReq proto.InternalMessageInfo

func (m *ChangeGroupMasterReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangeGroupMasterReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *ChangeGroupMasterReq) GetNewMaster() int64 {
	if m != nil {
		return m.NewMaster
	}
	return 0
}

type ChangeGroupMasterRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeGroupMasterRsp) Reset()         { *m = ChangeGroupMasterRsp{} }
func (m *ChangeGroupMasterRsp) String() string { return proto.CompactTextString(m) }
func (*ChangeGroupMasterRsp) ProtoMessage()    {}
func (*ChangeGroupMasterRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{5}
}

func (m *ChangeGroupMasterRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeGroupMasterRsp.Unmarshal(m, b)
}
func (m *ChangeGroupMasterRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeGroupMasterRsp.Marshal(b, m, deterministic)
}
func (m *ChangeGroupMasterRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeGroupMasterRsp.Merge(m, src)
}
func (m *ChangeGroupMasterRsp) XXX_Size() int {
	return xxx_messageInfo_ChangeGroupMasterRsp.Size(m)
}
func (m *ChangeGroupMasterRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeGroupMasterRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeGroupMasterRsp proto.InternalMessageInfo

func (m *ChangeGroupMasterRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChangeGroupMasterRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *ChangeGroupMasterRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type AddGroupMemberReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Members              []int64  `protobuf:"varint,3,rep,packed,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberReq) Reset()         { *m = AddGroupMemberReq{} }
func (m *AddGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberReq) ProtoMessage()    {}
func (*AddGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{6}
}

func (m *AddGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberReq.Unmarshal(m, b)
}
func (m *AddGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberReq.Merge(m, src)
}
func (m *AddGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberReq.Size(m)
}
func (m *AddGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberReq proto.InternalMessageInfo

func (m *AddGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *AddGroupMemberReq) GetMembers() []int64 {
	if m != nil {
		return m.Members
	}
	return nil
}

type AddGroupMemberRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddGroupMemberRsp) Reset()         { *m = AddGroupMemberRsp{} }
func (m *AddGroupMemberRsp) String() string { return proto.CompactTextString(m) }
func (*AddGroupMemberRsp) ProtoMessage()    {}
func (*AddGroupMemberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{7}
}

func (m *AddGroupMemberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddGroupMemberRsp.Unmarshal(m, b)
}
func (m *AddGroupMemberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddGroupMemberRsp.Marshal(b, m, deterministic)
}
func (m *AddGroupMemberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddGroupMemberRsp.Merge(m, src)
}
func (m *AddGroupMemberRsp) XXX_Size() int {
	return xxx_messageInfo_AddGroupMemberRsp.Size(m)
}
func (m *AddGroupMemberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddGroupMemberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AddGroupMemberRsp proto.InternalMessageInfo

func (m *AddGroupMemberRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AddGroupMemberRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *AddGroupMemberRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type RemoveGroupMemberReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Members              []int64  `protobuf:"varint,3,rep,packed,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveGroupMemberReq) Reset()         { *m = RemoveGroupMemberReq{} }
func (m *RemoveGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*RemoveGroupMemberReq) ProtoMessage()    {}
func (*RemoveGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{8}
}

func (m *RemoveGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveGroupMemberReq.Unmarshal(m, b)
}
func (m *RemoveGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *RemoveGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveGroupMemberReq.Merge(m, src)
}
func (m *RemoveGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_RemoveGroupMemberReq.Size(m)
}
func (m *RemoveGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveGroupMemberReq proto.InternalMessageInfo

func (m *RemoveGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RemoveGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *RemoveGroupMemberReq) GetMembers() []int64 {
	if m != nil {
		return m.Members
	}
	return nil
}

type RemoveGroupMemberRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveGroupMemberRsp) Reset()         { *m = RemoveGroupMemberRsp{} }
func (m *RemoveGroupMemberRsp) String() string { return proto.CompactTextString(m) }
func (*RemoveGroupMemberRsp) ProtoMessage()    {}
func (*RemoveGroupMemberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{9}
}

func (m *RemoveGroupMemberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveGroupMemberRsp.Unmarshal(m, b)
}
func (m *RemoveGroupMemberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveGroupMemberRsp.Marshal(b, m, deterministic)
}
func (m *RemoveGroupMemberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveGroupMemberRsp.Merge(m, src)
}
func (m *RemoveGroupMemberRsp) XXX_Size() int {
	return xxx_messageInfo_RemoveGroupMemberRsp.Size(m)
}
func (m *RemoveGroupMemberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveGroupMemberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveGroupMemberRsp proto.InternalMessageInfo

func (m *RemoveGroupMemberRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RemoveGroupMemberRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *RemoveGroupMemberRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type QuitGroupMemberReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupMemberReq) Reset()         { *m = QuitGroupMemberReq{} }
func (m *QuitGroupMemberReq) String() string { return proto.CompactTextString(m) }
func (*QuitGroupMemberReq) ProtoMessage()    {}
func (*QuitGroupMemberReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{10}
}

func (m *QuitGroupMemberReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupMemberReq.Unmarshal(m, b)
}
func (m *QuitGroupMemberReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupMemberReq.Marshal(b, m, deterministic)
}
func (m *QuitGroupMemberReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupMemberReq.Merge(m, src)
}
func (m *QuitGroupMemberReq) XXX_Size() int {
	return xxx_messageInfo_QuitGroupMemberReq.Size(m)
}
func (m *QuitGroupMemberReq) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupMemberReq.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupMemberReq proto.InternalMessageInfo

func (m *QuitGroupMemberReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QuitGroupMemberReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type QuitGroupMemberRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuitGroupMemberRsp) Reset()         { *m = QuitGroupMemberRsp{} }
func (m *QuitGroupMemberRsp) String() string { return proto.CompactTextString(m) }
func (*QuitGroupMemberRsp) ProtoMessage()    {}
func (*QuitGroupMemberRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{11}
}

func (m *QuitGroupMemberRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuitGroupMemberRsp.Unmarshal(m, b)
}
func (m *QuitGroupMemberRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuitGroupMemberRsp.Marshal(b, m, deterministic)
}
func (m *QuitGroupMemberRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuitGroupMemberRsp.Merge(m, src)
}
func (m *QuitGroupMemberRsp) XXX_Size() int {
	return xxx_messageInfo_QuitGroupMemberRsp.Size(m)
}
func (m *QuitGroupMemberRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_QuitGroupMemberRsp.DiscardUnknown(m)
}

var xxx_messageInfo_QuitGroupMemberRsp proto.InternalMessageInfo

func (m *QuitGroupMemberRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *QuitGroupMemberRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *QuitGroupMemberRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type GetGroupInfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupType            int32    `protobuf:"varint,2,opt,name=groupType,proto3" json:"groupType,omitempty"`
	Mute                 int32    `protobuf:"varint,3,opt,name=mute,proto3" json:"mute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupInfoReq) Reset()         { *m = GetGroupInfoReq{} }
func (m *GetGroupInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupInfoReq) ProtoMessage()    {}
func (*GetGroupInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{12}
}

func (m *GetGroupInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupInfoReq.Unmarshal(m, b)
}
func (m *GetGroupInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupInfoReq.Marshal(b, m, deterministic)
}
func (m *GetGroupInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupInfoReq.Merge(m, src)
}
func (m *GetGroupInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupInfoReq.Size(m)
}
func (m *GetGroupInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupInfoReq proto.InternalMessageInfo

func (m *GetGroupInfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetGroupInfoReq) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *GetGroupInfoReq) GetMute() int32 {
	if m != nil {
		return m.Mute
	}
	return 0
}

type GetGroupInfoRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Status               int32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	GroupType            int32    `protobuf:"varint,4,opt,name=groupType,proto3" json:"groupType,omitempty"`
	Mute                 int32    `protobuf:"varint,5,opt,name=mute,proto3" json:"mute,omitempty"`
	Master               int64    `protobuf:"varint,6,opt,name=master,proto3" json:"master,omitempty"`
	SecretKey            string   `protobuf:"bytes,7,opt,name=secretKey,proto3" json:"secretKey,omitempty"`
	SvcErr               int32    `protobuf:"varint,8,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupInfoRsp) Reset()         { *m = GetGroupInfoRsp{} }
func (m *GetGroupInfoRsp) String() string { return proto.CompactTextString(m) }
func (*GetGroupInfoRsp) ProtoMessage()    {}
func (*GetGroupInfoRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{13}
}

func (m *GetGroupInfoRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupInfoRsp.Unmarshal(m, b)
}
func (m *GetGroupInfoRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupInfoRsp.Marshal(b, m, deterministic)
}
func (m *GetGroupInfoRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupInfoRsp.Merge(m, src)
}
func (m *GetGroupInfoRsp) XXX_Size() int {
	return xxx_messageInfo_GetGroupInfoRsp.Size(m)
}
func (m *GetGroupInfoRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupInfoRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupInfoRsp proto.InternalMessageInfo

func (m *GetGroupInfoRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetGroupInfoRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetGroupInfoRsp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetGroupInfoRsp) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *GetGroupInfoRsp) GetMute() int32 {
	if m != nil {
		return m.Mute
	}
	return 0
}

func (m *GetGroupInfoRsp) GetMaster() int64 {
	if m != nil {
		return m.Master
	}
	return 0
}

func (m *GetGroupInfoRsp) GetSecretKey() string {
	if m != nil {
		return m.SecretKey
	}
	return ""
}

func (m *GetGroupInfoRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type GetGroupListReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGroupListReq) Reset()         { *m = GetGroupListReq{} }
func (m *GetGroupListReq) String() string { return proto.CompactTextString(m) }
func (*GetGroupListReq) ProtoMessage()    {}
func (*GetGroupListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{14}
}

func (m *GetGroupListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupListReq.Unmarshal(m, b)
}
func (m *GetGroupListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupListReq.Marshal(b, m, deterministic)
}
func (m *GetGroupListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupListReq.Merge(m, src)
}
func (m *GetGroupListReq) XXX_Size() int {
	return xxx_messageInfo_GetGroupListReq.Size(m)
}
func (m *GetGroupListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupListReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupListReq proto.InternalMessageInfo

func (m *GetGroupListReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetGroupListReq) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type GroupMemberInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role                 int32    `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Mute                 int32    `protobuf:"varint,3,opt,name=mute,proto3" json:"mute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMemberInfo) Reset()         { *m = GroupMemberInfo{} }
func (m *GroupMemberInfo) String() string { return proto.CompactTextString(m) }
func (*GroupMemberInfo) ProtoMessage()    {}
func (*GroupMemberInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{15}
}

func (m *GroupMemberInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMemberInfo.Unmarshal(m, b)
}
func (m *GroupMemberInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMemberInfo.Marshal(b, m, deterministic)
}
func (m *GroupMemberInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMemberInfo.Merge(m, src)
}
func (m *GroupMemberInfo) XXX_Size() int {
	return xxx_messageInfo_GroupMemberInfo.Size(m)
}
func (m *GroupMemberInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMemberInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMemberInfo proto.InternalMessageInfo

func (m *GroupMemberInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupMemberInfo) GetRole() int32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *GroupMemberInfo) GetMute() int32 {
	if m != nil {
		return m.Mute
	}
	return 0
}

type GetGroupListRsp struct {
	UserId               int64              `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GroupId              int64              `protobuf:"varint,2,opt,name=groupId,proto3" json:"groupId,omitempty"`
	List                 []*GroupMemberInfo `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	SvcErr               int32              `protobuf:"varint,4,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetGroupListRsp) Reset()         { *m = GetGroupListRsp{} }
func (m *GetGroupListRsp) String() string { return proto.CompactTextString(m) }
func (*GetGroupListRsp) ProtoMessage()    {}
func (*GetGroupListRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e10f4c9b19ad8eee, []int{16}
}

func (m *GetGroupListRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGroupListRsp.Unmarshal(m, b)
}
func (m *GetGroupListRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGroupListRsp.Marshal(b, m, deterministic)
}
func (m *GetGroupListRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGroupListRsp.Merge(m, src)
}
func (m *GetGroupListRsp) XXX_Size() int {
	return xxx_messageInfo_GetGroupListRsp.Size(m)
}
func (m *GetGroupListRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGroupListRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetGroupListRsp proto.InternalMessageInfo

func (m *GetGroupListRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetGroupListRsp) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GetGroupListRsp) GetList() []*GroupMemberInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *GetGroupListRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateGroupReq)(nil), "inner.CreateGroupReq")
	proto.RegisterType((*CreateGroupRsp)(nil), "inner.CreateGroupRsp")
	proto.RegisterType((*DismissGroupReq)(nil), "inner.DismissGroupReq")
	proto.RegisterType((*DismissGroupRsp)(nil), "inner.DismissGroupRsp")
	proto.RegisterType((*ChangeGroupMasterReq)(nil), "inner.ChangeGroupMasterReq")
	proto.RegisterType((*ChangeGroupMasterRsp)(nil), "inner.ChangeGroupMasterRsp")
	proto.RegisterType((*AddGroupMemberReq)(nil), "inner.AddGroupMemberReq")
	proto.RegisterType((*AddGroupMemberRsp)(nil), "inner.AddGroupMemberRsp")
	proto.RegisterType((*RemoveGroupMemberReq)(nil), "inner.RemoveGroupMemberReq")
	proto.RegisterType((*RemoveGroupMemberRsp)(nil), "inner.RemoveGroupMemberRsp")
	proto.RegisterType((*QuitGroupMemberReq)(nil), "inner.QuitGroupMemberReq")
	proto.RegisterType((*QuitGroupMemberRsp)(nil), "inner.QuitGroupMemberRsp")
	proto.RegisterType((*GetGroupInfoReq)(nil), "inner.GetGroupInfoReq")
	proto.RegisterType((*GetGroupInfoRsp)(nil), "inner.GetGroupInfoRsp")
	proto.RegisterType((*GetGroupListReq)(nil), "inner.GetGroupListReq")
	proto.RegisterType((*GroupMemberInfo)(nil), "inner.groupMemberInfo")
	proto.RegisterType((*GetGroupListRsp)(nil), "inner.GetGroupListRsp")
}

func init() { proto.RegisterFile("group.proto", fileDescriptor_e10f4c9b19ad8eee) }

var fileDescriptor_e10f4c9b19ad8eee = []byte{
	// 548 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x57, 0x48, 0xda, 0x6e, 0xaf, 0x68, 0xd5, 0xac, 0x31, 0x99, 0xc0, 0xa1, 0xca, 0xa9, 0xe2,
	0xd0, 0xc3, 0x38, 0x22, 0x21, 0x4d, 0x1d, 0x54, 0x15, 0xdb, 0x61, 0x11, 0x27, 0x26, 0x60, 0xed,
	0xe2, 0x95, 0x48, 0x4b, 0x62, 0x6c, 0x67, 0x68, 0x9f, 0x80, 0x2f, 0xc4, 0xa7, 0x81, 0x2f, 0x83,
	0x62, 0x3b, 0xcd, 0x3f, 0x47, 0x48, 0x21, 0x5c, 0xb8, 0xe5, 0xbd, 0x67, 0xff, 0xde, 0xef, 0xfd,
	0x12, 0xff, 0x1c, 0x18, 0x6f, 0x59, 0x92, 0xd2, 0x39, 0x65, 0x89, 0x48, 0xd0, 0x20, 0x8c, 0x63,
	0xc2, 0xbc, 0x0f, 0x70, 0xb0, 0x60, 0x64, 0x2d, 0xc8, 0x32, 0xab, 0xf9, 0xe4, 0x2b, 0x3a, 0x86,
	0x61, 0xca, 0x09, 0x5b, 0x05, 0xd8, 0x9a, 0x5a, 0x33, 0xdb, 0xd7, 0x11, 0x7a, 0x0e, 0xfb, 0x72,
	0xff, 0xfb, 0x07, 0x4a, 0xf0, 0xa3, 0xa9, 0x35, 0x1b, 0xf8, 0x45, 0x02, 0x21, 0x70, 0xa2, 0x54,
	0x10, 0x6c, 0xcb, 0x82, 0x7c, 0xf6, 0x7e, 0x5a, 0x55, 0x70, 0x4e, 0x5b, 0xc1, 0x31, 0x8c, 0x24,
	0xd6, 0x2a, 0x90, 0xd0, 0xb6, 0x9f, 0x87, 0xd9, 0x0e, 0x2e, 0xd6, 0x22, 0xe5, 0x1a, 0x5a, 0x47,
	0x55, 0x3a, 0x4e, 0x1b, 0x9d, 0x41, 0x41, 0x27, 0x43, 0x8a, 0xd6, 0x5c, 0x10, 0x86, 0x87, 0xaa,
	0xb7, 0x8a, 0x32, 0x24, 0x4e, 0x6e, 0x18, 0x11, 0xef, 0xc8, 0x03, 0x1e, 0x4d, 0xad, 0xd9, 0xbe,
	0x5f, 0x24, 0x64, 0xff, 0xfb, 0x9b, 0x37, 0x8c, 0xe1, 0x3d, 0xdd, 0x5f, 0x46, 0xde, 0x02, 0x26,
	0x67, 0x21, 0x8f, 0x42, 0xce, 0xff, 0xa8, 0x5c, 0xeb, 0x70, 0xde, 0x55, 0x0d, 0xa4, 0xb3, 0x42,
	0x8a, 0xa1, 0x5d, 0x61, 0x78, 0x0b, 0x47, 0x8b, 0x2f, 0xeb, 0x78, 0xab, 0xd4, 0xbf, 0x90, 0xc3,
	0x76, 0xa2, 0x99, 0x29, 0x14, 0x93, 0x6f, 0x0a, 0x41, 0x36, 0xb1, 0xfd, 0x22, 0xe1, 0x5d, 0x9b,
	0xfa, 0xf4, 0x3a, 0xc9, 0x67, 0x38, 0x3c, 0x0d, 0x02, 0x05, 0x4f, 0xa2, 0x4d, 0xd7, 0x31, 0x30,
	0x8c, 0x22, 0xb9, 0x3d, 0xfb, 0x96, 0xec, 0xac, 0xa2, 0x43, 0xef, 0x63, 0xa3, 0x41, 0xaf, 0xfc,
	0x37, 0x70, 0xe4, 0x93, 0x28, 0xb9, 0x27, 0xff, 0x70, 0x84, 0x6b, 0x53, 0x8f, 0x5e, 0xa7, 0x78,
	0x0b, 0xe8, 0x32, 0x0d, 0xc5, 0xdf, 0xce, 0xe0, 0x7d, 0x6a, 0xe2, 0xf4, 0xca, 0xf3, 0x0a, 0x26,
	0x4b, 0xa2, 0xe0, 0x57, 0xf1, 0x6d, 0xd2, 0xaf, 0xa7, 0xfd, 0xb2, 0x6a, 0xe8, 0xff, 0x9b, 0xa9,
	0xe5, 0xc3, 0x9d, 0x87, 0x5c, 0x74, 0x7b, 0xbf, 0x97, 0x30, 0xd9, 0x16, 0xef, 0x36, 0x13, 0xa9,
	0x15, 0x04, 0x81, 0xc3, 0x92, 0xbb, 0x5c, 0x7a, 0xf9, 0x6c, 0x54, 0xfd, 0xbb, 0x55, 0x23, 0xd6,
	0x49, 0xf5, 0x17, 0xe0, 0xdc, 0x85, 0x5c, 0xc8, 0x93, 0x33, 0x3e, 0x39, 0x9e, 0xcb, 0x1b, 0x70,
	0x5e, 0xe3, 0xea, 0xcb, 0x35, 0x25, 0x85, 0x9c, 0xb2, 0x42, 0x27, 0x3f, 0x1c, 0xd8, 0x3b, 0xa5,
	0xa1, 0x64, 0x82, 0x5e, 0xc1, 0xb8, 0x74, 0xbf, 0xa1, 0x27, 0x1a, 0xb1, 0x7a, 0xa1, 0xba, 0xa6,
	0x34, 0xa7, 0xe8, 0x35, 0x3c, 0x2e, 0x7b, 0x3f, 0xca, 0xf9, 0xd4, 0x6e, 0x15, 0xd7, 0x98, 0xe7,
	0x14, 0x5d, 0xc0, 0x61, 0xc3, 0x76, 0xd1, 0xb3, 0xbc, 0x97, 0xc1, 0xf8, 0xdd, 0xf6, 0x22, 0xa7,
	0xe8, 0x0c, 0x0e, 0xaa, 0x16, 0x88, 0xb0, 0x5e, 0xde, 0xb0, 0x5e, 0xb7, 0xa5, 0xa2, 0x48, 0x35,
	0x5c, 0x68, 0x47, 0xca, 0xe4, 0x81, 0x6e, 0x7b, 0x91, 0x53, 0xb4, 0x84, 0x49, 0xcd, 0x2a, 0xd0,
	0x53, 0xbd, 0xbe, 0x69, 0x45, 0x6e, 0x5b, 0x49, 0x89, 0x5d, 0x3e, 0xb5, 0x3b, 0xb1, 0x6b, 0x46,
	0xe1, 0x1a, 0xf3, 0xd5, 0xfd, 0xe7, 0xf2, 0xf3, 0xa8, 0xad, 0xd3, 0xa7, 0xc5, 0x35, 0xe6, 0x39,
	0xdd, 0x0c, 0xe5, 0x4f, 0xd7, 0xcb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x89, 0xe9, 0xc5,
	0x83, 0x09, 0x00, 0x00,
}
