// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ApiUser service

func NewApiUserEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ApiUser service

type ApiUserService interface {
	Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*RegisterRsp, error)
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRsp, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...client.CallOption) (*LogoutRsp, error)
	CheckToken(ctx context.Context, in *CheckTokenReq, opts ...client.CallOption) (*CheckTokenRsp, error)
}

type apiUserService struct {
	c    client.Client
	name string
}

func NewApiUserService(name string, c client.Client) ApiUserService {
	return &apiUserService{
		c:    c,
		name: name,
	}
}

func (c *apiUserService) Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*RegisterRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.Register", in)
	out := new(RegisterRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.Login", in)
	out := new(LoginRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) Logout(ctx context.Context, in *LogoutReq, opts ...client.CallOption) (*LogoutRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.Logout", in)
	out := new(LogoutRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiUserService) CheckToken(ctx context.Context, in *CheckTokenReq, opts ...client.CallOption) (*CheckTokenRsp, error) {
	req := c.c.NewRequest(c.name, "ApiUser.CheckToken", in)
	out := new(CheckTokenRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiUser service

type ApiUserHandler interface {
	Register(context.Context, *RegisterReq, *RegisterRsp) error
	Login(context.Context, *LoginReq, *LoginRsp) error
	Logout(context.Context, *LogoutReq, *LogoutRsp) error
	CheckToken(context.Context, *CheckTokenReq, *CheckTokenRsp) error
}

func RegisterApiUserHandler(s server.Server, hdlr ApiUserHandler, opts ...server.HandlerOption) error {
	type apiUser interface {
		Register(ctx context.Context, in *RegisterReq, out *RegisterRsp) error
		Login(ctx context.Context, in *LoginReq, out *LoginRsp) error
		Logout(ctx context.Context, in *LogoutReq, out *LogoutRsp) error
		CheckToken(ctx context.Context, in *CheckTokenReq, out *CheckTokenRsp) error
	}
	type ApiUser struct {
		apiUser
	}
	h := &apiUserHandler{hdlr}
	return s.Handle(s.NewHandler(&ApiUser{h}, opts...))
}

type apiUserHandler struct {
	ApiUserHandler
}

func (h *apiUserHandler) Register(ctx context.Context, in *RegisterReq, out *RegisterRsp) error {
	return h.ApiUserHandler.Register(ctx, in, out)
}

func (h *apiUserHandler) Login(ctx context.Context, in *LoginReq, out *LoginRsp) error {
	return h.ApiUserHandler.Login(ctx, in, out)
}

func (h *apiUserHandler) Logout(ctx context.Context, in *LogoutReq, out *LogoutRsp) error {
	return h.ApiUserHandler.Logout(ctx, in, out)
}

func (h *apiUserHandler) CheckToken(ctx context.Context, in *CheckTokenReq, out *CheckTokenRsp) error {
	return h.ApiUserHandler.CheckToken(ctx, in, out)
}
