// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RegisterRsp struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginToken           string   `protobuf:"bytes,3,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	SvcErr               int32    `protobuf:"varint,4,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRsp) Reset()         { *m = RegisterRsp{} }
func (m *RegisterRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterRsp) ProtoMessage()    {}
func (*RegisterRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *RegisterRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRsp.Unmarshal(m, b)
}
func (m *RegisterRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRsp.Marshal(b, m, deterministic)
}
func (m *RegisterRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRsp.Merge(m, src)
}
func (m *RegisterRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterRsp.Size(m)
}
func (m *RegisterRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRsp proto.InternalMessageInfo

func (m *RegisterRsp) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RegisterRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RegisterRsp) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

func (m *RegisterRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type LoginReq struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type LoginRsp struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginToken           string   `protobuf:"bytes,3,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	SvcErr               int32    `protobuf:"varint,4,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginRsp) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

func (m *LoginRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type LogoutReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginToken           string   `protobuf:"bytes,3,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutReq) Reset()         { *m = LogoutReq{} }
func (m *LogoutReq) String() string { return proto.CompactTextString(m) }
func (*LogoutReq) ProtoMessage()    {}
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LogoutReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutReq.Unmarshal(m, b)
}
func (m *LogoutReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutReq.Marshal(b, m, deterministic)
}
func (m *LogoutReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutReq.Merge(m, src)
}
func (m *LogoutReq) XXX_Size() int {
	return xxx_messageInfo_LogoutReq.Size(m)
}
func (m *LogoutReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutReq proto.InternalMessageInfo

func (m *LogoutReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LogoutReq) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

type LogoutRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SvcErr               int32    `protobuf:"varint,2,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRsp) Reset()         { *m = LogoutRsp{} }
func (m *LogoutRsp) String() string { return proto.CompactTextString(m) }
func (*LogoutRsp) ProtoMessage()    {}
func (*LogoutRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *LogoutRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRsp.Unmarshal(m, b)
}
func (m *LogoutRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRsp.Marshal(b, m, deterministic)
}
func (m *LogoutRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRsp.Merge(m, src)
}
func (m *LogoutRsp) XXX_Size() int {
	return xxx_messageInfo_LogoutRsp.Size(m)
}
func (m *LogoutRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRsp proto.InternalMessageInfo

func (m *LogoutRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LogoutRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

type CheckTokenReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginToken           string   `protobuf:"bytes,2,opt,name=loginToken,proto3" json:"loginToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenReq) Reset()         { *m = CheckTokenReq{} }
func (m *CheckTokenReq) String() string { return proto.CompactTextString(m) }
func (*CheckTokenReq) ProtoMessage()    {}
func (*CheckTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *CheckTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenReq.Unmarshal(m, b)
}
func (m *CheckTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenReq.Marshal(b, m, deterministic)
}
func (m *CheckTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenReq.Merge(m, src)
}
func (m *CheckTokenReq) XXX_Size() int {
	return xxx_messageInfo_CheckTokenReq.Size(m)
}
func (m *CheckTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenReq proto.InternalMessageInfo

func (m *CheckTokenReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckTokenReq) GetLoginToken() string {
	if m != nil {
		return m.LoginToken
	}
	return ""
}

type CheckTokenRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TokenStatus          int32    `protobuf:"varint,2,opt,name=TokenStatus,proto3" json:"TokenStatus,omitempty"`
	SvcErr               int32    `protobuf:"varint,3,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTokenRsp) Reset()         { *m = CheckTokenRsp{} }
func (m *CheckTokenRsp) String() string { return proto.CompactTextString(m) }
func (*CheckTokenRsp) ProtoMessage()    {}
func (*CheckTokenRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *CheckTokenRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTokenRsp.Unmarshal(m, b)
}
func (m *CheckTokenRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTokenRsp.Marshal(b, m, deterministic)
}
func (m *CheckTokenRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTokenRsp.Merge(m, src)
}
func (m *CheckTokenRsp) XXX_Size() int {
	return xxx_messageInfo_CheckTokenRsp.Size(m)
}
func (m *CheckTokenRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTokenRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTokenRsp proto.InternalMessageInfo

func (m *CheckTokenRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckTokenRsp) GetTokenStatus() int32 {
	if m != nil {
		return m.TokenStatus
	}
	return 0
}

func (m *CheckTokenRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "inner.RegisterReq")
	proto.RegisterType((*RegisterRsp)(nil), "inner.RegisterRsp")
	proto.RegisterType((*LoginReq)(nil), "inner.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "inner.LoginRsp")
	proto.RegisterType((*LogoutReq)(nil), "inner.LogoutReq")
	proto.RegisterType((*LogoutRsp)(nil), "inner.LogoutRsp")
	proto.RegisterType((*CheckTokenReq)(nil), "inner.CheckTokenReq")
	proto.RegisterType((*CheckTokenRsp)(nil), "inner.CheckTokenRsp")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xd6, 0xa4, 0xed, 0x14, 0x51, 0x06, 0x91, 0x90, 0x83, 0x84, 0x20, 0x18, 0x41,
	0x72, 0xa8, 0x17, 0xc1, 0x93, 0x14, 0x11, 0xa1, 0xa7, 0xa8, 0x0f, 0x10, 0xe3, 0x12, 0x43, 0x25,
	0xbb, 0xee, 0x6c, 0xf4, 0x35, 0x7d, 0x24, 0xc9, 0x36, 0x31, 0x1b, 0x6b, 0x8b, 0x5e, 0x3c, 0xce,
	0x3f, 0xff, 0xfe, 0xf9, 0xb2, 0x33, 0x0b, 0x50, 0x11, 0x57, 0xb1, 0x54, 0x42, 0x0b, 0x74, 0x8a,
	0xb2, 0xe4, 0x2a, 0x3c, 0x81, 0x69, 0xc2, 0xf3, 0x82, 0x34, 0x57, 0x09, 0x7f, 0x45, 0x0f, 0x46,
	0x69, 0x96, 0x89, 0xaa, 0xd4, 0x1e, 0x0b, 0x58, 0x34, 0x49, 0xda, 0x32, 0x7c, 0xb7, 0x8c, 0x24,
	0x37, 0x1b, 0xf1, 0x10, 0xdc, 0xfa, 0x33, 0xb7, 0x4f, 0xde, 0x20, 0x60, 0xd1, 0x30, 0x69, 0x2a,
	0x3c, 0x02, 0x78, 0x11, 0x79, 0x51, 0xde, 0x8b, 0x25, 0x2f, 0xbd, 0xa1, 0x39, 0x64, 0x29, 0xf5,
	0x39, 0x7a, 0xcb, 0xae, 0x95, 0xf2, 0x76, 0x02, 0x16, 0x39, 0x49, 0x53, 0x85, 0xc7, 0x30, 0x5e,
	0xd4, 0xae, 0xed, 0x78, 0xba, 0x75, 0xfd, 0x2b, 0xdb, 0x1c, 0x26, 0x0b, 0x91, 0x8b, 0x4a, 0xd7,
	0x70, 0x5d, 0x38, 0xfb, 0x4b, 0x78, 0x78, 0xf9, 0x15, 0x42, 0x72, 0x63, 0x48, 0x47, 0x30, 0xe8,
	0x11, 0xdc, 0xc0, 0xee, 0xfc, 0x99, 0x67, 0x4b, 0x13, 0xf5, 0x7b, 0x8a, 0xc1, 0x1a, 0x45, 0xda,
	0x0b, 0xda, 0x42, 0x12, 0xc0, 0xd4, 0x78, 0xee, 0x74, 0xaa, 0x2b, 0x6a, 0x70, 0x6c, 0xc9, 0x62,
	0x1d, 0xda, 0xac, 0xb3, 0x0f, 0x06, 0xa3, 0x2b, 0x59, 0x3c, 0x10, 0x57, 0x38, 0x83, 0x71, 0xbb,
	0x4e, 0x88, 0xb1, 0xd9, 0xc5, 0xd8, 0x5a, 0x44, 0x7f, 0x4d, 0x23, 0x89, 0xa7, 0xe0, 0x98, 0x19,
	0xe3, 0x5e, 0xd3, 0x6c, 0xf7, 0xc2, 0xef, 0x0b, 0x24, 0xf1, 0x0c, 0xdc, 0xd5, 0x9d, 0xe2, 0x7e,
	0xd7, 0x5a, 0xcd, 0xc9, 0xff, 0xa6, 0x90, 0xc4, 0x0b, 0x80, 0xee, 0xdf, 0xf1, 0xa0, 0xe9, 0xf7,
	0xee, 0xd5, 0xff, 0x41, 0x25, 0xf9, 0xe8, 0x9a, 0xc7, 0x74, 0xfe, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x3e, 0x7e, 0x02, 0xd4, 0x5a, 0x03, 0x00, 0x00,
}
