// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ApiGroup service

func NewApiGroupEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ApiGroup service

type ApiGroupService interface {
	Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*RegisterRsp, error)
	Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRsp, error)
	Logout(ctx context.Context, in *LogoutReq, opts ...client.CallOption) (*LogoutRsp, error)
	CheckToken(ctx context.Context, in *CheckTokenReq, opts ...client.CallOption) (*CheckTokenRsp, error)
}

type apiGroupService struct {
	c    client.Client
	name string
}

func NewApiGroupService(name string, c client.Client) ApiGroupService {
	return &apiGroupService{
		c:    c,
		name: name,
	}
}

func (c *apiGroupService) Register(ctx context.Context, in *RegisterReq, opts ...client.CallOption) (*RegisterRsp, error) {
	req := c.c.NewRequest(c.name, "ApiGroup.Register", in)
	out := new(RegisterRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiGroupService) Login(ctx context.Context, in *LoginReq, opts ...client.CallOption) (*LoginRsp, error) {
	req := c.c.NewRequest(c.name, "ApiGroup.Login", in)
	out := new(LoginRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiGroupService) Logout(ctx context.Context, in *LogoutReq, opts ...client.CallOption) (*LogoutRsp, error) {
	req := c.c.NewRequest(c.name, "ApiGroup.Logout", in)
	out := new(LogoutRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiGroupService) CheckToken(ctx context.Context, in *CheckTokenReq, opts ...client.CallOption) (*CheckTokenRsp, error) {
	req := c.c.NewRequest(c.name, "ApiGroup.CheckToken", in)
	out := new(CheckTokenRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiGroup service

type ApiGroupHandler interface {
	Register(context.Context, *RegisterReq, *RegisterRsp) error
	Login(context.Context, *LoginReq, *LoginRsp) error
	Logout(context.Context, *LogoutReq, *LogoutRsp) error
	CheckToken(context.Context, *CheckTokenReq, *CheckTokenRsp) error
}

func RegisterApiGroupHandler(s server.Server, hdlr ApiGroupHandler, opts ...server.HandlerOption) error {
	type apiGroup interface {
		Register(ctx context.Context, in *RegisterReq, out *RegisterRsp) error
		Login(ctx context.Context, in *LoginReq, out *LoginRsp) error
		Logout(ctx context.Context, in *LogoutReq, out *LogoutRsp) error
		CheckToken(ctx context.Context, in *CheckTokenReq, out *CheckTokenRsp) error
	}
	type ApiGroup struct {
		apiGroup
	}
	h := &apiGroupHandler{hdlr}
	return s.Handle(s.NewHandler(&ApiGroup{h}, opts...))
}

type apiGroupHandler struct {
	ApiGroupHandler
}

func (h *apiGroupHandler) Register(ctx context.Context, in *RegisterReq, out *RegisterRsp) error {
	return h.ApiGroupHandler.Register(ctx, in, out)
}

func (h *apiGroupHandler) Login(ctx context.Context, in *LoginReq, out *LoginRsp) error {
	return h.ApiGroupHandler.Login(ctx, in, out)
}

func (h *apiGroupHandler) Logout(ctx context.Context, in *LogoutReq, out *LogoutRsp) error {
	return h.ApiGroupHandler.Logout(ctx, in, out)
}

func (h *apiGroupHandler) CheckToken(ctx context.Context, in *CheckTokenReq, out *CheckTokenRsp) error {
	return h.ApiGroupHandler.CheckToken(ctx, in, out)
}
