// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gateway.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientInfo struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginType            int32    `protobuf:"varint,2,opt,name=loginType,proto3" json:"loginType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{0}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ClientInfo) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

type PushMsgReq struct {
	Clients              []*ClientInfo `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	Content              []byte        `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PushMsgReq) Reset()         { *m = PushMsgReq{} }
func (m *PushMsgReq) String() string { return proto.CompactTextString(m) }
func (*PushMsgReq) ProtoMessage()    {}
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{1}
}

func (m *PushMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgReq.Unmarshal(m, b)
}
func (m *PushMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgReq.Marshal(b, m, deterministic)
}
func (m *PushMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgReq.Merge(m, src)
}
func (m *PushMsgReq) XXX_Size() int {
	return xxx_messageInfo_PushMsgReq.Size(m)
}
func (m *PushMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgReq proto.InternalMessageInfo

func (m *PushMsgReq) GetClients() []*ClientInfo {
	if m != nil {
		return m.Clients
	}
	return nil
}

func (m *PushMsgReq) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PushMsgRsp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsgRsp) Reset()         { *m = PushMsgRsp{} }
func (m *PushMsgRsp) String() string { return proto.CompactTextString(m) }
func (*PushMsgRsp) ProtoMessage()    {}
func (*PushMsgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_f1a937782ebbded5, []int{2}
}

func (m *PushMsgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsgRsp.Unmarshal(m, b)
}
func (m *PushMsgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsgRsp.Marshal(b, m, deterministic)
}
func (m *PushMsgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsgRsp.Merge(m, src)
}
func (m *PushMsgRsp) XXX_Size() int {
	return xxx_messageInfo_PushMsgRsp.Size(m)
}
func (m *PushMsgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsgRsp proto.InternalMessageInfo

func (m *PushMsgRsp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *PushMsgRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*ClientInfo)(nil), "inner.ClientInfo")
	proto.RegisterType((*PushMsgReq)(nil), "inner.PushMsgReq")
	proto.RegisterType((*PushMsgRsp)(nil), "inner.PushMsgRsp")
}

func init() { proto.RegisterFile("gateway.proto", fileDescriptor_f1a937782ebbded5) }

var fileDescriptor_f1a937782ebbded5 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4b, 0x87, 0x30,
	0x14, 0xc7, 0x59, 0xf6, 0x53, 0x7c, 0x15, 0xd5, 0x3b, 0xc4, 0x88, 0x0e, 0xe2, 0x49, 0x08, 0x3c,
	0xd8, 0xa1, 0x7b, 0x05, 0xe1, 0x21, 0x88, 0xe5, 0x3f, 0x60, 0xba, 0x96, 0xa0, 0xdb, 0x72, 0x93,
	0xf0, 0xbf, 0x8f, 0xa6, 0x63, 0xf0, 0xbb, 0xbd, 0xf7, 0x65, 0x7c, 0xbe, 0x9f, 0x3d, 0xb8, 0x10,
	0xad, 0xe5, 0xbf, 0xed, 0x5a, 0xea, 0x59, 0x59, 0x85, 0x87, 0x41, 0x4a, 0x3e, 0xe7, 0x4f, 0x00,
	0xcf, 0xe3, 0xc0, 0xa5, 0xad, 0xe5, 0x97, 0xc2, 0x1b, 0x88, 0x17, 0xc3, 0xe7, 0xba, 0xa7, 0x24,
	0x23, 0x45, 0xc4, 0xf6, 0x0d, 0xef, 0x20, 0x1d, 0x95, 0x18, 0x64, 0xb3, 0x6a, 0x4e, 0x4f, 0x32,
	0x52, 0x1c, 0x58, 0x08, 0xf2, 0x0f, 0x80, 0xf7, 0xc5, 0x7c, 0xbf, 0x19, 0xc1, 0xf8, 0x0f, 0xde,
	0x43, 0xd2, 0x39, 0xa2, 0xa1, 0x24, 0x8b, 0x8a, 0xb3, 0xea, 0xba, 0x74, 0x55, 0x65, 0xe8, 0x61,
	0xfe, 0x05, 0x52, 0x48, 0x3a, 0x25, 0x2d, 0x97, 0xd6, 0x61, 0xcf, 0x99, 0x5f, 0xf3, 0x2a, 0x40,
	0x8d, 0xc6, 0x2b, 0x88, 0x26, 0x23, 0x9c, 0x55, 0xca, 0xfe, 0x47, 0x44, 0x38, 0xed, 0x54, 0xef,
	0x6d, 0xdc, 0x5c, 0xbd, 0x40, 0x5a, 0x4f, 0xaf, 0xdb, 0x37, 0xf1, 0x11, 0x2e, 0x77, 0x40, 0xa3,
	0xb6, 0x6a, 0xf4, 0x26, 0xc1, 0xf6, 0xf6, 0x38, 0x32, 0xfa, 0x33, 0x76, 0x07, 0x7a, 0xf8, 0x0b,
	0x00, 0x00, 0xff, 0xff, 0xeb, 0x6d, 0xe9, 0x90, 0x31, 0x01, 0x00, 0x00,
}
