// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: gateway.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for ImGateway service

func NewImGatewayEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for ImGateway service

type ImGatewayService interface {
	PushMsgToClient(ctx context.Context, in *PushMsgReq, opts ...client.CallOption) (*PushMsgRsp, error)
}

type imGatewayService struct {
	c    client.Client
	name string
}

func NewImGatewayService(name string, c client.Client) ImGatewayService {
	return &imGatewayService{
		c:    c,
		name: name,
	}
}

func (c *imGatewayService) PushMsgToClient(ctx context.Context, in *PushMsgReq, opts ...client.CallOption) (*PushMsgRsp, error) {
	req := c.c.NewRequest(c.name, "ImGateway.PushMsgToClient", in)
	out := new(PushMsgRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ImGateway service

type ImGatewayHandler interface {
	PushMsgToClient(context.Context, *PushMsgReq, *PushMsgRsp) error
}

func RegisterImGatewayHandler(s server.Server, hdlr ImGatewayHandler, opts ...server.HandlerOption) error {
	type imGateway interface {
		PushMsgToClient(ctx context.Context, in *PushMsgReq, out *PushMsgRsp) error
	}
	type ImGateway struct {
		imGateway
	}
	h := &imGatewayHandler{hdlr}
	return s.Handle(s.NewHandler(&ImGateway{h}, opts...))
}

type imGatewayHandler struct {
	ImGatewayHandler
}

func (h *imGatewayHandler) PushMsgToClient(ctx context.Context, in *PushMsgReq, out *PushMsgRsp) error {
	return h.ImGatewayHandler.PushMsgToClient(ctx, in, out)
}
