// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package inner

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginType            int32    `protobuf:"varint,2,opt,name=loginType,proto3" json:"loginType,omitempty"`
	RoleType             int32    `protobuf:"varint,3,opt,name=roleType,proto3" json:"roleType,omitempty"`
	Command              int32    `protobuf:"varint,4,opt,name=command,proto3" json:"command,omitempty"`
	Content              []byte   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	LinkToken            string   `protobuf:"bytes,6,opt,name=linkToken,proto3" json:"linkToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginReq) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LoginReq) GetRoleType() int32 {
	if m != nil {
		return m.RoleType
	}
	return 0
}

func (m *LoginReq) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *LoginReq) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *LoginReq) GetLinkToken() string {
	if m != nil {
		return m.LinkToken
	}
	return ""
}

type LoginRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	LoginType            int32    `protobuf:"varint,2,opt,name=loginType,proto3" json:"loginType,omitempty"`
	RoleType             int32    `protobuf:"varint,3,opt,name=roleType,proto3" json:"roleType,omitempty"`
	Command              int32    `protobuf:"varint,4,opt,name=command,proto3" json:"command,omitempty"`
	Content              []byte   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	SvcErr               int32    `protobuf:"varint,6,opt,name=svcErr,proto3" json:"svcErr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginRsp) GetLoginType() int32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LoginRsp) GetRoleType() int32 {
	if m != nil {
		return m.RoleType
	}
	return 0
}

func (m *LoginRsp) GetCommand() int32 {
	if m != nil {
		return m.Command
	}
	return 0
}

func (m *LoginRsp) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *LoginRsp) GetSvcErr() int32 {
	if m != nil {
		return m.SvcErr
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "inner.loginReq")
	proto.RegisterType((*LoginRsp)(nil), "inner.loginRsp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcd, 0xcc, 0xcb, 0x4b, 0x2d, 0x52, 0x5a,
	0xc7, 0xc8, 0xc5, 0x01, 0x16, 0x0e, 0x4a, 0x2d, 0x14, 0x12, 0xe3, 0x62, 0x2b, 0x2d, 0x4e, 0x2d,
	0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x82, 0xf2, 0x84, 0x64, 0xb8, 0x38, 0xc1,
	0x6a, 0x42, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x10, 0x02, 0x42, 0x52,
	0x5c, 0x1c, 0x45, 0xf9, 0x39, 0xa9, 0x60, 0x49, 0x66, 0xb0, 0x24, 0x9c, 0x2f, 0x24, 0xc1, 0xc5,
	0x9e, 0x9c, 0x9f, 0x9b, 0x9b, 0x98, 0x97, 0x22, 0xc1, 0x02, 0x96, 0x82, 0x71, 0x21, 0x32, 0x79,
	0x25, 0xa9, 0x79, 0x25, 0x12, 0xac, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x30, 0x2e, 0xd8, 0xb6, 0xcc,
	0xbc, 0xec, 0x90, 0xfc, 0xec, 0xd4, 0x3c, 0x09, 0x36, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x84, 0x80,
	0xd2, 0x0a, 0xb8, 0x83, 0x8b, 0x0b, 0x06, 0x89, 0x83, 0xc5, 0xb8, 0xd8, 0x8a, 0xcb, 0x92, 0x5d,
	0x8b, 0x8a, 0xc0, 0xae, 0x65, 0x0d, 0x82, 0xf2, 0x8c, 0x4c, 0xb8, 0xd8, 0x3d, 0x73, 0x7d, 0x40,
	0xd6, 0x0a, 0x69, 0x72, 0xb1, 0x42, 0x18, 0xfc, 0x7a, 0xe0, 0x70, 0xd7, 0x83, 0x85, 0xb9, 0x14,
	0xaa, 0x40, 0x71, 0x41, 0x12, 0x1b, 0x38, 0x7e, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed,
	0x4e, 0x13, 0x48, 0xae, 0x01, 0x00, 0x00,
}
