// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.content.proto

package im_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Content struct {
	MsgType              int32    `protobuf:"varint,1,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Content) Reset()         { *m = Content{} }
func (m *Content) String() string { return proto.CompactTextString(m) }
func (*Content) ProtoMessage()    {}
func (*Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{0}
}

func (m *Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Content.Unmarshal(m, b)
}
func (m *Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Content.Marshal(b, m, deterministic)
}
func (m *Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Content.Merge(m, src)
}
func (m *Content) XXX_Size() int {
	return xxx_messageInfo_Content.Size(m)
}
func (m *Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Content proto.InternalMessageInfo

func (m *Content) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Content) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Text struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Text) Reset()         { *m = Text{} }
func (m *Text) String() string { return proto.CompactTextString(m) }
func (*Text) ProtoMessage()    {}
func (*Text) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{1}
}

func (m *Text) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Text.Unmarshal(m, b)
}
func (m *Text) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Text.Marshal(b, m, deterministic)
}
func (m *Text) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Text.Merge(m, src)
}
func (m *Text) XXX_Size() int {
	return xxx_messageInfo_Text.Size(m)
}
func (m *Text) XXX_DiscardUnknown() {
	xxx_messageInfo_Text.DiscardUnknown(m)
}

var xxx_messageInfo_Text proto.InternalMessageInfo

func (m *Text) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Emoji struct {
	EmojiType            int32    `protobuf:"varint,1,opt,name=emojiType,proto3" json:"emojiType,omitempty"`
	EmojiNumber          int32    `protobuf:"varint,2,opt,name=emojiNumber,proto3" json:"emojiNumber,omitempty"`
	EmojiUrl             string   `protobuf:"bytes,3,opt,name=emojiUrl,proto3" json:"emojiUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emoji) Reset()         { *m = Emoji{} }
func (m *Emoji) String() string { return proto.CompactTextString(m) }
func (*Emoji) ProtoMessage()    {}
func (*Emoji) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{2}
}

func (m *Emoji) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emoji.Unmarshal(m, b)
}
func (m *Emoji) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emoji.Marshal(b, m, deterministic)
}
func (m *Emoji) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emoji.Merge(m, src)
}
func (m *Emoji) XXX_Size() int {
	return xxx_messageInfo_Emoji.Size(m)
}
func (m *Emoji) XXX_DiscardUnknown() {
	xxx_messageInfo_Emoji.DiscardUnknown(m)
}

var xxx_messageInfo_Emoji proto.InternalMessageInfo

func (m *Emoji) GetEmojiType() int32 {
	if m != nil {
		return m.EmojiType
	}
	return 0
}

func (m *Emoji) GetEmojiNumber() int32 {
	if m != nil {
		return m.EmojiNumber
	}
	return 0
}

func (m *Emoji) GetEmojiUrl() string {
	if m != nil {
		return m.EmojiUrl
	}
	return ""
}

type Image struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width                int32    `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Extension            string   `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{3}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Image) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

type File struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	FileName             string   `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Size                 int32    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Extension            string   `protobuf:"bytes,4,opt,name=extension,proto3" json:"extension,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetExtension() string {
	if m != nil {
		return m.Extension
	}
	return ""
}

type Audio struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Audio) Reset()         { *m = Audio{} }
func (m *Audio) String() string { return proto.CompactTextString(m) }
func (*Audio) ProtoMessage()    {}
func (*Audio) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{5}
}

func (m *Audio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Audio.Unmarshal(m, b)
}
func (m *Audio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Audio.Marshal(b, m, deterministic)
}
func (m *Audio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Audio.Merge(m, src)
}
func (m *Audio) XXX_Size() int {
	return xxx_messageInfo_Audio.Size(m)
}
func (m *Audio) XXX_DiscardUnknown() {
	xxx_messageInfo_Audio.DiscardUnknown(m)
}

var xxx_messageInfo_Audio proto.InternalMessageInfo

func (m *Audio) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Audio) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Video struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Duration             int32    `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a3496478a65ff29, []int{6}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Video) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Video) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*Content)(nil), "im.app.content")
	proto.RegisterType((*Text)(nil), "im.app.text")
	proto.RegisterType((*Emoji)(nil), "im.app.emoji")
	proto.RegisterType((*Image)(nil), "im.app.image")
	proto.RegisterType((*File)(nil), "im.app.file")
	proto.RegisterType((*Audio)(nil), "im.app.audio")
	proto.RegisterType((*Video)(nil), "im.app.video")
}

func init() { proto.RegisterFile("im.content.proto", fileDescriptor_9a3496478a65ff29) }

var fileDescriptor_9a3496478a65ff29 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x6e, 0x83, 0x30,
	0x10, 0x87, 0x45, 0xc0, 0x24, 0x5c, 0x3b, 0x44, 0x56, 0x55, 0x59, 0x51, 0x07, 0xc4, 0x94, 0xa5,
	0x2c, 0x9d, 0xfb, 0x00, 0x5d, 0x32, 0xa0, 0xf6, 0x01, 0x48, 0x70, 0xe0, 0x2a, 0x8c, 0x11, 0x98,
	0x36, 0xe9, 0xd3, 0x57, 0xbe, 0xf0, 0x4f, 0x55, 0x2a, 0x65, 0xbb, 0xef, 0xee, 0xfc, 0xfb, 0x6e,
	0x30, 0xac, 0x51, 0xc5, 0x07, 0x5d, 0x19, 0x59, 0x99, 0xb8, 0x6e, 0xb4, 0xd1, 0xdc, 0x47, 0x15,
	0xa7, 0x75, 0x1d, 0xbd, 0xc2, 0xb2, 0x1f, 0x70, 0x01, 0x4b, 0xd5, 0xe6, 0xef, 0xe7, 0x5a, 0x0a,
	0x27, 0x74, 0xb6, 0x2c, 0x19, 0xd0, 0x4e, 0xfa, 0x25, 0xb1, 0x08, 0x9d, 0xed, 0x7d, 0x32, 0x60,
	0x14, 0x82, 0x67, 0xe4, 0xc9, 0xcc, 0x37, 0xec, 0xdb, 0x60, 0xda, 0x38, 0x00, 0x93, 0x4a, 0x7f,
	0x22, 0x7f, 0x82, 0x80, 0x8a, 0x99, 0x60, 0x6a, 0xf0, 0x10, 0xee, 0x08, 0x76, 0x9d, 0xda, 0xcb,
	0x86, 0x34, 0x2c, 0x99, 0xb7, 0xf8, 0x06, 0x56, 0x84, 0x1f, 0x4d, 0x29, 0x5c, 0x72, 0x8c, 0x1c,
	0x9d, 0x81, 0xa1, 0x4a, 0x73, 0xc9, 0xd7, 0xe0, 0x76, 0x4d, 0xd9, 0xdf, 0x60, 0x4b, 0xfe, 0x00,
	0xec, 0x1b, 0x33, 0x53, 0xf4, 0x91, 0x17, 0xe0, 0x8f, 0xe0, 0x17, 0x12, 0xf3, 0xc2, 0x50, 0x14,
	0x4b, 0x7a, 0xe2, 0x1c, 0xbc, 0x16, 0x7f, 0xa4, 0xf0, 0xa8, 0x4b, 0x35, 0x1d, 0x7e, 0x32, 0xb2,
	0x6a, 0x51, 0x57, 0x82, 0x51, 0xf2, 0xd4, 0x88, 0x8e, 0xe0, 0x1d, 0xb1, 0xbc, 0x66, 0xde, 0xc0,
	0xca, 0x4e, 0x76, 0xa9, 0x92, 0x24, 0x0f, 0x92, 0x91, 0x47, 0x8f, 0xfb, 0x9f, 0xc7, 0xfb, 0xeb,
	0x79, 0x06, 0x96, 0x76, 0x19, 0xea, 0x2b, 0xa2, 0x21, 0x6c, 0x31, 0x85, 0x45, 0x6f, 0xc0, 0xbe,
	0x30, 0x93, 0x37, 0xae, 0xdb, 0x5b, 0xb3, 0xae, 0x49, 0x8d, 0x55, 0x5f, 0x6e, 0x1a, 0x79, 0xef,
	0xd3, 0x8f, 0x79, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xdd, 0xf6, 0xd5, 0x45, 0x02, 0x00,
	0x00,
}
