// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.group.proto

package im_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GroupMsg struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	FromId               int64    `protobuf:"varint,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	MsgId                string   `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ServerId             string   `protobuf:"bytes,5,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Encrypt              int32    `protobuf:"varint,6,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Content              []byte   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AtCount              int32    `protobuf:"varint,9,opt,name=atCount,proto3" json:"atCount,omitempty"`
	AtUsers              []int64  `protobuf:"varint,10,rep,packed,name=atUsers,proto3" json:"atUsers,omitempty"`
	Extend               []byte   `protobuf:"bytes,11,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMsg) Reset()         { *m = GroupMsg{} }
func (m *GroupMsg) String() string { return proto.CompactTextString(m) }
func (*GroupMsg) ProtoMessage()    {}
func (*GroupMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{0}
}

func (m *GroupMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMsg.Unmarshal(m, b)
}
func (m *GroupMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMsg.Marshal(b, m, deterministic)
}
func (m *GroupMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMsg.Merge(m, src)
}
func (m *GroupMsg) XXX_Size() int {
	return xxx_messageInfo_GroupMsg.Size(m)
}
func (m *GroupMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMsg proto.InternalMessageInfo

func (m *GroupMsg) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupMsg) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GroupMsg) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *GroupMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupMsg) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *GroupMsg) GetEncrypt() int32 {
	if m != nil {
		return m.Encrypt
	}
	return 0
}

func (m *GroupMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GroupMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GroupMsg) GetAtCount() int32 {
	if m != nil {
		return m.AtCount
	}
	return 0
}

func (m *GroupMsg) GetAtUsers() []int64 {
	if m != nil {
		return m.AtUsers
	}
	return nil
}

func (m *GroupMsg) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

type GroupAck struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ServerId             string   `protobuf:"bytes,4,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrCode              int32    `protobuf:"varint,6,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupAck) Reset()         { *m = GroupAck{} }
func (m *GroupAck) String() string { return proto.CompactTextString(m) }
func (*GroupAck) ProtoMessage()    {}
func (*GroupAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{1}
}

func (m *GroupAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupAck.Unmarshal(m, b)
}
func (m *GroupAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupAck.Marshal(b, m, deterministic)
}
func (m *GroupAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupAck.Merge(m, src)
}
func (m *GroupAck) XXX_Size() int {
	return xxx_messageInfo_GroupAck.Size(m)
}
func (m *GroupAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupAck.DiscardUnknown(m)
}

var xxx_messageInfo_GroupAck proto.InternalMessageInfo

func (m *GroupAck) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupAck) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupAck) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *GroupAck) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GroupAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type GroupDeliverAck struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ServerId             string   `protobuf:"bytes,4,opt,name=serverId,proto3" json:"serverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupDeliverAck) Reset()         { *m = GroupDeliverAck{} }
func (m *GroupDeliverAck) String() string { return proto.CompactTextString(m) }
func (*GroupDeliverAck) ProtoMessage()    {}
func (*GroupDeliverAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{2}
}

func (m *GroupDeliverAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDeliverAck.Unmarshal(m, b)
}
func (m *GroupDeliverAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDeliverAck.Marshal(b, m, deterministic)
}
func (m *GroupDeliverAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDeliverAck.Merge(m, src)
}
func (m *GroupDeliverAck) XXX_Size() int {
	return xxx_messageInfo_GroupDeliverAck.Size(m)
}
func (m *GroupDeliverAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDeliverAck.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDeliverAck proto.InternalMessageInfo

func (m *GroupDeliverAck) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupDeliverAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupDeliverAck) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupDeliverAck) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func init() {
	proto.RegisterType((*GroupMsg)(nil), "im.app.groupMsg")
	proto.RegisterType((*GroupAck)(nil), "im.app.groupAck")
	proto.RegisterType((*GroupDeliverAck)(nil), "im.app.groupDeliverAck")
}

func init() { proto.RegisterFile("im.group.proto", fileDescriptor_64b73c85c2e8e110) }

var fileDescriptor_64b73c85c2e8e110 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0x87, 0xc9, 0xba, 0x76, 0x5b, 0x14, 0x85, 0x20, 0xe3, 0x45, 0x3c, 0x94, 0x9d, 0x7a, 0xda,
	0xc5, 0x4f, 0x20, 0xf3, 0xd2, 0x83, 0x97, 0x82, 0x1f, 0x60, 0x2e, 0xaf, 0x23, 0x68, 0x9a, 0xf0,
	0x26, 0x1d, 0xee, 0x0b, 0x89, 0x1f, 0x53, 0x92, 0xb4, 0x1d, 0x8a, 0x7a, 0xf4, 0xd6, 0x27, 0x2f,
	0xef, 0x9f, 0xdf, 0x43, 0xf9, 0x85, 0xd2, 0xeb, 0x3d, 0x99, 0xce, 0xae, 0x2d, 0x19, 0x6f, 0x44,
	0xa1, 0xf4, 0x7a, 0x6b, 0xed, 0xea, 0x63, 0xc2, 0xe7, 0xf1, 0xfd, 0xc1, 0xed, 0x05, 0xf0, 0x59,
	0xfc, 0xae, 0x25, 0xb0, 0x92, 0x55, 0x59, 0x33, 0xa0, 0xb8, 0xe6, 0x73, 0x4b, 0xca, 0x90, 0xf2,
	0x47, 0x98, 0x94, 0xac, 0xca, 0x9b, 0x91, 0xc5, 0x92, 0x17, 0xcf, 0x64, 0x74, 0x2d, 0x21, 0x8b,
	0x4d, 0x3d, 0x89, 0x2b, 0x9e, 0x6b, 0xb7, 0xaf, 0x25, 0x4c, 0x4b, 0x56, 0x2d, 0x9a, 0x04, 0x61,
	0x92, 0x43, 0x3a, 0x20, 0xd5, 0x12, 0xf2, 0x58, 0x18, 0x39, 0xec, 0xc7, 0x76, 0x47, 0x47, 0xeb,
	0xa1, 0x88, 0x4b, 0x06, 0x0c, 0x95, 0x9d, 0x69, 0x3d, 0xb6, 0x1e, 0x66, 0x25, 0xab, 0xce, 0x9b,
	0x01, 0xc5, 0x0d, 0x5f, 0x78, 0xa5, 0xd1, 0xf9, 0xad, 0xb6, 0x30, 0x8f, 0x07, 0x9c, 0x1e, 0x42,
	0xdf, 0xd6, 0x6f, 0x4c, 0xd7, 0x7a, 0x58, 0xa4, 0x89, 0x3d, 0xa6, 0xca, 0xa3, 0x43, 0x72, 0xc0,
	0xcb, 0x2c, 0x64, 0xed, 0x31, 0xe4, 0xc1, 0x37, 0x8f, 0xad, 0x84, 0xb3, 0xb8, 0xaa, 0xa7, 0xd5,
	0x3b, 0xeb, 0x55, 0xdd, 0xed, 0x5e, 0xfe, 0x50, 0xb5, 0xe4, 0x45, 0xe7, 0x62, 0xbc, 0x49, 0xd2,
	0x91, 0xe8, 0xa4, 0x23, 0xfb, 0x4d, 0xc7, 0xf4, 0x9b, 0x8e, 0x2f, 0xd1, 0xf2, 0x1f, 0xa2, 0x21,
	0xd1, 0xc6, 0x48, 0x1c, 0x65, 0x25, 0x5c, 0x75, 0xfc, 0x32, 0x1e, 0x73, 0x8f, 0xaf, 0xea, 0x80,
	0xf4, 0x4f, 0xe7, 0x3e, 0x15, 0xf1, 0xcf, 0xba, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xce, 0xe8,
	0xae, 0x95, 0x6b, 0x02, 0x00, 0x00,
}
