// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.group.proto

package im_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/////////////////////////////////////
// cmd_group_msg = 0x1001;
/////////////////////////////////////
type GroupMsg struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupType            int32    `protobuf:"varint,2,opt,name=groupType,proto3" json:"groupType,omitempty"`
	FromId               int64    `protobuf:"varint,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	Priority             int32    `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,5,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	MsgId                string   `protobuf:"bytes,6,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Encrypt              int32    `protobuf:"varint,7,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Content              []byte   `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	MsgTime              int64    `protobuf:"varint,9,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	AtCount              int32    `protobuf:"varint,10,opt,name=atCount,proto3" json:"atCount,omitempty"`
	AtUsers              []int64  `protobuf:"varint,11,rep,packed,name=atUsers,proto3" json:"atUsers,omitempty"`
	Extend               []byte   `protobuf:"bytes,12,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMsg) Reset()         { *m = GroupMsg{} }
func (m *GroupMsg) String() string { return proto.CompactTextString(m) }
func (*GroupMsg) ProtoMessage()    {}
func (*GroupMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{0}
}

func (m *GroupMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMsg.Unmarshal(m, b)
}
func (m *GroupMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMsg.Marshal(b, m, deterministic)
}
func (m *GroupMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMsg.Merge(m, src)
}
func (m *GroupMsg) XXX_Size() int {
	return xxx_messageInfo_GroupMsg.Size(m)
}
func (m *GroupMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMsg proto.InternalMessageInfo

func (m *GroupMsg) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupMsg) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *GroupMsg) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *GroupMsg) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *GroupMsg) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *GroupMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupMsg) GetEncrypt() int32 {
	if m != nil {
		return m.Encrypt
	}
	return 0
}

func (m *GroupMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *GroupMsg) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

func (m *GroupMsg) GetAtCount() int32 {
	if m != nil {
		return m.AtCount
	}
	return 0
}

func (m *GroupMsg) GetAtUsers() []int64 {
	if m != nil {
		return m.AtUsers
	}
	return nil
}

func (m *GroupMsg) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

type GroupAck struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,3,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	MsgId                string   `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgTime              int64    `protobuf:"varint,5,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	ErrCode              int32    `protobuf:"varint,6,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupAck) Reset()         { *m = GroupAck{} }
func (m *GroupAck) String() string { return proto.CompactTextString(m) }
func (*GroupAck) ProtoMessage()    {}
func (*GroupAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{1}
}

func (m *GroupAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupAck.Unmarshal(m, b)
}
func (m *GroupAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupAck.Marshal(b, m, deterministic)
}
func (m *GroupAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupAck.Merge(m, src)
}
func (m *GroupAck) XXX_Size() int {
	return xxx_messageInfo_GroupAck.Size(m)
}
func (m *GroupAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupAck.DiscardUnknown(m)
}

var xxx_messageInfo_GroupAck proto.InternalMessageInfo

func (m *GroupAck) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupAck) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *GroupAck) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupAck) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

func (m *GroupAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type GroupDeliverAck struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupType            int32    `protobuf:"varint,2,opt,name=groupType,proto3" json:"groupType,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgIds               []string `protobuf:"bytes,4,rep,name=msgIds,proto3" json:"msgIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupDeliverAck) Reset()         { *m = GroupDeliverAck{} }
func (m *GroupDeliverAck) String() string { return proto.CompactTextString(m) }
func (*GroupDeliverAck) ProtoMessage()    {}
func (*GroupDeliverAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{2}
}

func (m *GroupDeliverAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupDeliverAck.Unmarshal(m, b)
}
func (m *GroupDeliverAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupDeliverAck.Marshal(b, m, deterministic)
}
func (m *GroupDeliverAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupDeliverAck.Merge(m, src)
}
func (m *GroupDeliverAck) XXX_Size() int {
	return xxx_messageInfo_GroupDeliverAck.Size(m)
}
func (m *GroupDeliverAck) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupDeliverAck.DiscardUnknown(m)
}

var xxx_messageInfo_GroupDeliverAck proto.InternalMessageInfo

func (m *GroupDeliverAck) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupDeliverAck) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *GroupDeliverAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupDeliverAck) GetMsgIds() []string {
	if m != nil {
		return m.MsgIds
	}
	return nil
}

/////////////////////////////////////////////
// cmd_group_open = 0x1005;
// cmd_group_join = 0x1009;
// cmd_group_remove = 0x100d;
// cmd_group_quit = 0x10
// cmd_group_close = 0x1015;
////////////////////////////////////////////
type GroupOperator struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupType            int32    `protobuf:"varint,2,opt,name=groupType,proto3" json:"groupType,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,4,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	MsgId                string   `protobuf:"bytes,5,opt,name=msgId,proto3" json:"msgId,omitempty"`
	MsgTime              int64    `protobuf:"varint,6,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	Extend               string   `protobuf:"bytes,7,opt,name=extend,proto3" json:"extend,omitempty"`
	OtherId              []int64  `protobuf:"varint,8,rep,packed,name=otherId,proto3" json:"otherId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupOperator) Reset()         { *m = GroupOperator{} }
func (m *GroupOperator) String() string { return proto.CompactTextString(m) }
func (*GroupOperator) ProtoMessage()    {}
func (*GroupOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{3}
}

func (m *GroupOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupOperator.Unmarshal(m, b)
}
func (m *GroupOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupOperator.Marshal(b, m, deterministic)
}
func (m *GroupOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupOperator.Merge(m, src)
}
func (m *GroupOperator) XXX_Size() int {
	return xxx_messageInfo_GroupOperator.Size(m)
}
func (m *GroupOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupOperator.DiscardUnknown(m)
}

var xxx_messageInfo_GroupOperator proto.InternalMessageInfo

func (m *GroupOperator) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupOperator) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *GroupOperator) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GroupOperator) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *GroupOperator) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupOperator) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

func (m *GroupOperator) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *GroupOperator) GetOtherId() []int64 {
	if m != nil {
		return m.OtherId
	}
	return nil
}

/////////////////////////////////////
// cmd_group_msg = 0x1019;
/////////////////////////////////////
type GroupMsgCancel struct {
	GroupId              int64    `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	GroupType            int32    `protobuf:"varint,2,opt,name=groupType,proto3" json:"groupType,omitempty"`
	FromId               int64    `protobuf:"varint,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,4,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	MsgId                string   `protobuf:"bytes,5,opt,name=msgId,proto3" json:"msgId,omitempty"`
	CancelMsgId          string   `protobuf:"bytes,6,opt,name=cancelMsgId,proto3" json:"cancelMsgId,omitempty"`
	MsgTime              int64    `protobuf:"varint,7,opt,name=msgTime,proto3" json:"msgTime,omitempty"`
	Extend               []byte   `protobuf:"bytes,8,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupMsgCancel) Reset()         { *m = GroupMsgCancel{} }
func (m *GroupMsgCancel) String() string { return proto.CompactTextString(m) }
func (*GroupMsgCancel) ProtoMessage()    {}
func (*GroupMsgCancel) Descriptor() ([]byte, []int) {
	return fileDescriptor_64b73c85c2e8e110, []int{4}
}

func (m *GroupMsgCancel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupMsgCancel.Unmarshal(m, b)
}
func (m *GroupMsgCancel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupMsgCancel.Marshal(b, m, deterministic)
}
func (m *GroupMsgCancel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupMsgCancel.Merge(m, src)
}
func (m *GroupMsgCancel) XXX_Size() int {
	return xxx_messageInfo_GroupMsgCancel.Size(m)
}
func (m *GroupMsgCancel) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupMsgCancel.DiscardUnknown(m)
}

var xxx_messageInfo_GroupMsgCancel proto.InternalMessageInfo

func (m *GroupMsgCancel) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *GroupMsgCancel) GetGroupType() int32 {
	if m != nil {
		return m.GroupType
	}
	return 0
}

func (m *GroupMsgCancel) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *GroupMsgCancel) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *GroupMsgCancel) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *GroupMsgCancel) GetCancelMsgId() string {
	if m != nil {
		return m.CancelMsgId
	}
	return ""
}

func (m *GroupMsgCancel) GetMsgTime() int64 {
	if m != nil {
		return m.MsgTime
	}
	return 0
}

func (m *GroupMsgCancel) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

func init() {
	proto.RegisterType((*GroupMsg)(nil), "im.app.groupMsg")
	proto.RegisterType((*GroupAck)(nil), "im.app.groupAck")
	proto.RegisterType((*GroupDeliverAck)(nil), "im.app.groupDeliverAck")
	proto.RegisterType((*GroupOperator)(nil), "im.app.groupOperator")
	proto.RegisterType((*GroupMsgCancel)(nil), "im.app.groupMsgCancel")
}

func init() { proto.RegisterFile("im.group.proto", fileDescriptor_64b73c85c2e8e110) }

var fileDescriptor_64b73c85c2e8e110 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4d, 0x4e, 0xeb, 0x30,
	0x10, 0x80, 0xe5, 0xe6, 0xdf, 0xed, 0xeb, 0x93, 0x22, 0x54, 0x59, 0x88, 0x45, 0x94, 0x55, 0x56,
	0xdd, 0x70, 0x02, 0x54, 0x36, 0x59, 0x54, 0x48, 0x51, 0x39, 0x40, 0x48, 0x4c, 0x88, 0x68, 0x62,
	0xcb, 0x71, 0x11, 0xb9, 0x11, 0x47, 0xe1, 0x1e, 0x6c, 0x39, 0x04, 0xf2, 0xc4, 0xa1, 0x69, 0x51,
	0x83, 0x84, 0xba, 0xcb, 0x37, 0xa3, 0xb1, 0x67, 0x3e, 0xdb, 0xc1, 0xf3, 0xb2, 0x5a, 0x16, 0x82,
	0xed, 0xf8, 0x92, 0x0b, 0x26, 0x99, 0x6f, 0x97, 0xd5, 0x32, 0xe5, 0x3c, 0x7c, 0x9f, 0x60, 0x17,
	0xe2, 0xeb, 0xa6, 0xf0, 0x09, 0x76, 0xe0, 0x3b, 0xce, 0x09, 0x0a, 0x50, 0x64, 0x24, 0x3d, 0xfa,
	0x57, 0xd8, 0x83, 0xcf, 0x4d, 0xcb, 0x29, 0x99, 0x04, 0x28, 0xb2, 0x92, 0x7d, 0xc0, 0x5f, 0x60,
	0xfb, 0x51, 0xb0, 0x2a, 0xce, 0x89, 0x01, 0x65, 0x9a, 0xfc, 0x4b, 0xec, 0x72, 0x51, 0x32, 0x51,
	0xca, 0x96, 0x98, 0x50, 0xf4, 0xcd, 0x7e, 0x80, 0xa7, 0xd9, 0xb6, 0xa4, 0xb5, 0x5c, 0x37, 0x45,
	0x9c, 0x13, 0x2b, 0x40, 0x91, 0x97, 0x0c, 0x43, 0xfe, 0x05, 0xb6, 0x2a, 0xc8, 0xd9, 0x90, 0xeb,
	0x40, 0xf5, 0x48, 0xeb, 0x4c, 0xb4, 0x5c, 0x12, 0x07, 0x96, 0xec, 0x51, 0x65, 0x32, 0x56, 0x4b,
	0x5a, 0x4b, 0xe2, 0x06, 0x28, 0x9a, 0x25, 0x3d, 0xaa, 0x4c, 0xd5, 0x14, 0x9b, 0xb2, 0xa2, 0xc4,
	0xeb, 0xe6, 0xd2, 0xa8, 0x32, 0xa9, 0x5c, 0xb1, 0x5d, 0x2d, 0x09, 0xee, 0x56, 0xd3, 0xd8, 0x65,
	0xee, 0x1b, 0x2a, 0x1a, 0x32, 0x0d, 0x0c, 0x55, 0xa3, 0x51, 0x4d, 0x4b, 0x5f, 0x25, 0xad, 0x73,
	0x32, 0x83, 0x6d, 0x34, 0x85, 0x6f, 0x48, 0xab, 0xbc, 0xc9, 0x9e, 0x47, 0x54, 0x2e, 0xb0, 0xbd,
	0x6b, 0xa8, 0x88, 0x73, 0xf0, 0x68, 0x24, 0x9a, 0x8e, 0x85, 0x18, 0x23, 0x42, 0xcc, 0x23, 0x21,
	0xfd, 0x70, 0xd6, 0x8f, 0xe1, 0xa8, 0x10, 0x2b, 0x96, 0x53, 0x50, 0xa8, 0x54, 0x75, 0x18, 0xb6,
	0xf8, 0x3f, 0xb4, 0x73, 0x4b, 0xb7, 0xe5, 0x0b, 0x15, 0xe3, 0x0d, 0xff, 0x7a, 0xf6, 0x7a, 0x1c,
	0xe3, 0x60, 0x9c, 0x05, 0xb6, 0xa1, 0xbf, 0x86, 0x98, 0x81, 0x11, 0x79, 0x89, 0xa6, 0xf0, 0x03,
	0xe1, 0x7f, 0x50, 0x7d, 0xc7, 0xa9, 0x48, 0x25, 0x13, 0x67, 0xdf, 0xf9, 0x48, 0xa4, 0x39, 0x22,
	0xd2, 0x3a, 0x21, 0xd2, 0x3e, 0x14, 0xb9, 0x3f, 0x71, 0x07, 0x0a, 0x34, 0xa9, 0x0a, 0x26, 0x9f,
	0xa0, 0x05, 0xb7, 0xbb, 0x23, 0x1a, 0xc3, 0x4f, 0x84, 0xe7, 0xfd, 0xb3, 0x5a, 0xa5, 0x75, 0x46,
	0xb7, 0x67, 0x7f, 0x5c, 0x7f, 0x1d, 0x53, 0xd5, 0x41, 0x47, 0xeb, 0xc1, 0xe3, 0x1a, 0x86, 0x86,
	0x22, 0x9c, 0x53, 0x22, 0xdc, 0xe1, 0xd5, 0x7f, 0xb0, 0xe1, 0xa7, 0x72, 0xfd, 0x15, 0x00, 0x00,
	0xff, 0xff, 0x9e, 0xb8, 0xd3, 0x4e, 0x66, 0x04, 0x00, 0x00,
}
