// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.room.proto

package im_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomMsg struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	FromId               int64    `protobuf:"varint,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	MsgId                string   `protobuf:"bytes,4,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ServerId             string   `protobuf:"bytes,5,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Encrypt              int32    `protobuf:"varint,6,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Content              []byte   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AtCount              int32    `protobuf:"varint,9,opt,name=atCount,proto3" json:"atCount,omitempty"`
	AtUsers              []int64  `protobuf:"varint,10,rep,packed,name=atUsers,proto3" json:"atUsers,omitempty"`
	Extend               []byte   `protobuf:"bytes,11,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMsg) Reset()         { *m = RoomMsg{} }
func (m *RoomMsg) String() string { return proto.CompactTextString(m) }
func (*RoomMsg) ProtoMessage()    {}
func (*RoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{0}
}

func (m *RoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMsg.Unmarshal(m, b)
}
func (m *RoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMsg.Marshal(b, m, deterministic)
}
func (m *RoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMsg.Merge(m, src)
}
func (m *RoomMsg) XXX_Size() int {
	return xxx_messageInfo_RoomMsg.Size(m)
}
func (m *RoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMsg proto.InternalMessageInfo

func (m *RoomMsg) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomMsg) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *RoomMsg) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *RoomMsg) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *RoomMsg) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *RoomMsg) GetEncrypt() int32 {
	if m != nil {
		return m.Encrypt
	}
	return 0
}

func (m *RoomMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RoomMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomMsg) GetAtCount() int32 {
	if m != nil {
		return m.AtCount
	}
	return 0
}

func (m *RoomMsg) GetAtUsers() []int64 {
	if m != nil {
		return m.AtUsers
	}
	return nil
}

func (m *RoomMsg) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

type RoomAck struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ServerId             string   `protobuf:"bytes,4,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrCode              int32    `protobuf:"varint,6,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAck) Reset()         { *m = RoomAck{} }
func (m *RoomAck) String() string { return proto.CompactTextString(m) }
func (*RoomAck) ProtoMessage()    {}
func (*RoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{1}
}

func (m *RoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAck.Unmarshal(m, b)
}
func (m *RoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAck.Marshal(b, m, deterministic)
}
func (m *RoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAck.Merge(m, src)
}
func (m *RoomAck) XXX_Size() int {
	return xxx_messageInfo_RoomAck.Size(m)
}
func (m *RoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAck proto.InternalMessageInfo

func (m *RoomAck) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomAck) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *RoomAck) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

func (m *RoomAck) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type RoomDeliverAck struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	ServerId             string   `protobuf:"bytes,4,opt,name=serverId,proto3" json:"serverId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomDeliverAck) Reset()         { *m = RoomDeliverAck{} }
func (m *RoomDeliverAck) String() string { return proto.CompactTextString(m) }
func (*RoomDeliverAck) ProtoMessage()    {}
func (*RoomDeliverAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{2}
}

func (m *RoomDeliverAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDeliverAck.Unmarshal(m, b)
}
func (m *RoomDeliverAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDeliverAck.Marshal(b, m, deterministic)
}
func (m *RoomDeliverAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDeliverAck.Merge(m, src)
}
func (m *RoomDeliverAck) XXX_Size() int {
	return xxx_messageInfo_RoomDeliverAck.Size(m)
}
func (m *RoomDeliverAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDeliverAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDeliverAck proto.InternalMessageInfo

func (m *RoomDeliverAck) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomDeliverAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomDeliverAck) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *RoomDeliverAck) GetServerId() string {
	if m != nil {
		return m.ServerId
	}
	return ""
}

type RoomOpen struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Extend               string   `protobuf:"bytes,5,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomOpen) Reset()         { *m = RoomOpen{} }
func (m *RoomOpen) String() string { return proto.CompactTextString(m) }
func (*RoomOpen) ProtoMessage()    {}
func (*RoomOpen) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{3}
}

func (m *RoomOpen) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomOpen.Unmarshal(m, b)
}
func (m *RoomOpen) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomOpen.Marshal(b, m, deterministic)
}
func (m *RoomOpen) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomOpen.Merge(m, src)
}
func (m *RoomOpen) XXX_Size() int {
	return xxx_messageInfo_RoomOpen.Size(m)
}
func (m *RoomOpen) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomOpen.DiscardUnknown(m)
}

var xxx_messageInfo_RoomOpen proto.InternalMessageInfo

func (m *RoomOpen) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomOpen) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomOpen) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *RoomOpen) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomOpen) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

type RoomJoin struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MsgId                string   `protobuf:"bytes,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Extend               string   `protobuf:"bytes,5,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomJoin) Reset()         { *m = RoomJoin{} }
func (m *RoomJoin) String() string { return proto.CompactTextString(m) }
func (*RoomJoin) ProtoMessage()    {}
func (*RoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{4}
}

func (m *RoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomJoin.Unmarshal(m, b)
}
func (m *RoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomJoin.Marshal(b, m, deterministic)
}
func (m *RoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomJoin.Merge(m, src)
}
func (m *RoomJoin) XXX_Size() int {
	return xxx_messageInfo_RoomJoin.Size(m)
}
func (m *RoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_RoomJoin proto.InternalMessageInfo

func (m *RoomJoin) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomJoin) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomJoin) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *RoomJoin) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomJoin) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func init() {
	proto.RegisterType((*RoomMsg)(nil), "im.app.roomMsg")
	proto.RegisterType((*RoomAck)(nil), "im.app.roomAck")
	proto.RegisterType((*RoomDeliverAck)(nil), "im.app.roomDeliverAck")
	proto.RegisterType((*RoomOpen)(nil), "im.app.roomOpen")
	proto.RegisterType((*RoomJoin)(nil), "im.app.roomJoin")
}

func init() { proto.RegisterFile("im.room.proto", fileDescriptor_e54fd61032f5bb56) }

var fileDescriptor_e54fd61032f5bb56 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x93, 0xcd, 0x4a, 0x3b, 0x31,
	0x14, 0xc5, 0x49, 0xa7, 0x33, 0x6d, 0xf3, 0xff, 0xeb, 0x22, 0x48, 0x09, 0xe2, 0x62, 0x98, 0xd5,
	0xac, 0xba, 0xf1, 0x09, 0xa4, 0x6e, 0x2a, 0x88, 0x30, 0xe0, 0x03, 0xd4, 0x99, 0x6b, 0x09, 0x9a,
	0x0f, 0x6e, 0xd2, 0x62, 0x5f, 0xc0, 0x17, 0x11, 0xdf, 0x53, 0x92, 0xcc, 0x07, 0x2d, 0x76, 0x27,
	0xba, 0xeb, 0xef, 0x5e, 0xee, 0xbd, 0xe7, 0x9c, 0x74, 0xe8, 0x99, 0x90, 0x0b, 0xd4, 0x5a, 0x2e,
	0x0c, 0x6a, 0xa7, 0x59, 0x26, 0xe4, 0x62, 0x6d, 0x4c, 0xf1, 0x39, 0xa2, 0x13, 0x5f, 0xbe, 0xb7,
	0x1b, 0x36, 0xa7, 0x99, 0xff, 0xb9, 0x6a, 0x38, 0xc9, 0x49, 0x99, 0x54, 0x2d, 0xb1, 0x4b, 0x3a,
	0x35, 0x28, 0x34, 0x0a, 0xb7, 0xe7, 0xa3, 0x9c, 0x94, 0x69, 0xd5, 0xb3, 0x9f, 0x79, 0xc6, 0x30,
	0x93, 0xc4, 0x99, 0x48, 0xec, 0x82, 0xa6, 0xd2, 0x6e, 0x56, 0x0d, 0x1f, 0xe7, 0xa4, 0x9c, 0x55,
	0x11, 0xfc, 0x26, 0x0b, 0xb8, 0x03, 0x5c, 0x35, 0x3c, 0x0d, 0x8d, 0x9e, 0x19, 0xa7, 0x13, 0x50,
	0x35, 0xee, 0x8d, 0xe3, 0x59, 0x38, 0xd2, 0xa1, 0xef, 0xd4, 0x5a, 0x39, 0x50, 0x8e, 0x4f, 0x72,
	0x52, 0xfe, 0xaf, 0x3a, 0x64, 0x57, 0x74, 0xe6, 0x84, 0x04, 0xeb, 0xd6, 0xd2, 0xf0, 0x69, 0x10,
	0x30, 0x14, 0xfc, 0xdc, 0xda, 0x2d, 0xf5, 0x56, 0x39, 0x3e, 0x8b, 0x1b, 0x5b, 0x8c, 0x9d, 0x47,
	0x0b, 0x68, 0x39, 0xcd, 0x93, 0x32, 0xa9, 0x3a, 0xf4, 0x7e, 0xe0, 0xcd, 0x81, 0x6a, 0xf8, 0xbf,
	0x70, 0xaa, 0xa5, 0xe2, 0x83, 0xc4, 0x9c, 0x6e, 0xea, 0x97, 0x93, 0x39, 0xcd, 0x69, 0xb6, 0xb5,
	0xc1, 0xdb, 0x28, 0xd6, 0x23, 0x0d, 0x59, 0x24, 0xa7, 0xb2, 0x18, 0x1f, 0x65, 0x71, 0xe0, 0x2b,
	0xfd, 0xc6, 0x17, 0x20, 0x2e, 0x75, 0x03, 0x7d, 0x52, 0x11, 0x0b, 0xa4, 0xe7, 0x5e, 0xcb, 0x2d,
	0xbc, 0x8a, 0x1d, 0xe0, 0xaf, 0x68, 0x2d, 0xde, 0x09, 0x9d, 0xfa, 0xa5, 0x0f, 0x06, 0xd4, 0x0f,
	0x9d, 0x3b, 0xb0, 0x3f, 0x3e, 0xb6, 0x3f, 0x3c, 0x51, 0xfc, 0x0b, 0x75, 0x4f, 0xd4, 0x09, 0xb9,
	0xd3, 0xe2, 0x4f, 0x85, 0x3c, 0x65, 0xe1, 0x13, 0xbb, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0x26, 0xec, 0x89, 0x73, 0x03, 0x00, 0x00,
}
