// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.room.proto

package im_app

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

/////////////////////////////////////
// cmd_room_msg = 0x1001;
/////////////////////////////////////
type RoomMsg struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	FromId               int64    `protobuf:"varint,3,opt,name=fromId,proto3" json:"fromId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,4,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	ServerMsgId          string   `protobuf:"bytes,5,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	Encrypt              int32    `protobuf:"varint,6,opt,name=encrypt,proto3" json:"encrypt,omitempty"`
	Content              []byte   `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AtCount              int32    `protobuf:"varint,9,opt,name=atCount,proto3" json:"atCount,omitempty"`
	AtUsers              []int64  `protobuf:"varint,10,rep,packed,name=atUsers,proto3" json:"atUsers,omitempty"`
	Extend               []byte   `protobuf:"bytes,11,opt,name=extend,proto3" json:"extend,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomMsg) Reset()         { *m = RoomMsg{} }
func (m *RoomMsg) String() string { return proto.CompactTextString(m) }
func (*RoomMsg) ProtoMessage()    {}
func (*RoomMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{0}
}

func (m *RoomMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomMsg.Unmarshal(m, b)
}
func (m *RoomMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomMsg.Marshal(b, m, deterministic)
}
func (m *RoomMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomMsg.Merge(m, src)
}
func (m *RoomMsg) XXX_Size() int {
	return xxx_messageInfo_RoomMsg.Size(m)
}
func (m *RoomMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RoomMsg proto.InternalMessageInfo

func (m *RoomMsg) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomMsg) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *RoomMsg) GetFromId() int64 {
	if m != nil {
		return m.FromId
	}
	return 0
}

func (m *RoomMsg) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *RoomMsg) GetServerMsgId() string {
	if m != nil {
		return m.ServerMsgId
	}
	return ""
}

func (m *RoomMsg) GetEncrypt() int32 {
	if m != nil {
		return m.Encrypt
	}
	return 0
}

func (m *RoomMsg) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RoomMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomMsg) GetAtCount() int32 {
	if m != nil {
		return m.AtCount
	}
	return 0
}

func (m *RoomMsg) GetAtUsers() []int64 {
	if m != nil {
		return m.AtUsers
	}
	return nil
}

func (m *RoomMsg) GetExtend() []byte {
	if m != nil {
		return m.Extend
	}
	return nil
}

type RoomAck struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,3,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	ServerMsgId          string   `protobuf:"bytes,4,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrCode              int32    `protobuf:"varint,6,opt,name=errCode,proto3" json:"errCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomAck) Reset()         { *m = RoomAck{} }
func (m *RoomAck) String() string { return proto.CompactTextString(m) }
func (*RoomAck) ProtoMessage()    {}
func (*RoomAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{1}
}

func (m *RoomAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomAck.Unmarshal(m, b)
}
func (m *RoomAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomAck.Marshal(b, m, deterministic)
}
func (m *RoomAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomAck.Merge(m, src)
}
func (m *RoomAck) XXX_Size() int {
	return xxx_messageInfo_RoomAck.Size(m)
}
func (m *RoomAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoomAck proto.InternalMessageInfo

func (m *RoomAck) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomAck) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *RoomAck) GetServerMsgId() string {
	if m != nil {
		return m.ServerMsgId
	}
	return ""
}

func (m *RoomAck) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomAck) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

type RoomDeliverAck struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ServerMsgId          []string `protobuf:"bytes,3,rep,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomDeliverAck) Reset()         { *m = RoomDeliverAck{} }
func (m *RoomDeliverAck) String() string { return proto.CompactTextString(m) }
func (*RoomDeliverAck) ProtoMessage()    {}
func (*RoomDeliverAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{2}
}

func (m *RoomDeliverAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomDeliverAck.Unmarshal(m, b)
}
func (m *RoomDeliverAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomDeliverAck.Marshal(b, m, deterministic)
}
func (m *RoomDeliverAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomDeliverAck.Merge(m, src)
}
func (m *RoomDeliverAck) XXX_Size() int {
	return xxx_messageInfo_RoomDeliverAck.Size(m)
}
func (m *RoomDeliverAck) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomDeliverAck.DiscardUnknown(m)
}

var xxx_messageInfo_RoomDeliverAck proto.InternalMessageInfo

func (m *RoomDeliverAck) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomDeliverAck) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomDeliverAck) GetServerMsgId() []string {
	if m != nil {
		return m.ServerMsgId
	}
	return nil
}

/////////////////////////////////////////////
// cmd_room_open = 0x1005;
// cmd_room_join = 0x1009;
// cmd_room_remove = 0x100d;
// cmd_room_quit = 0x10
// cmd_room_close = 0x1015;
////////////////////////////////////////////
type RoomOperator struct {
	RoomId               int64    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ClientMsgId          string   `protobuf:"bytes,3,opt,name=clientMsgId,proto3" json:"clientMsgId,omitempty"`
	ServerMsgId          string   `protobuf:"bytes,4,opt,name=serverMsgId,proto3" json:"serverMsgId,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Extend               string   `protobuf:"bytes,6,opt,name=extend,proto3" json:"extend,omitempty"`
	OtherId              []int64  `protobuf:"varint,7,rep,packed,name=otherId,proto3" json:"otherId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomOperator) Reset()         { *m = RoomOperator{} }
func (m *RoomOperator) String() string { return proto.CompactTextString(m) }
func (*RoomOperator) ProtoMessage()    {}
func (*RoomOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_e54fd61032f5bb56, []int{3}
}

func (m *RoomOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomOperator.Unmarshal(m, b)
}
func (m *RoomOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomOperator.Marshal(b, m, deterministic)
}
func (m *RoomOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomOperator.Merge(m, src)
}
func (m *RoomOperator) XXX_Size() int {
	return xxx_messageInfo_RoomOperator.Size(m)
}
func (m *RoomOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomOperator.DiscardUnknown(m)
}

var xxx_messageInfo_RoomOperator proto.InternalMessageInfo

func (m *RoomOperator) GetRoomId() int64 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *RoomOperator) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RoomOperator) GetClientMsgId() string {
	if m != nil {
		return m.ClientMsgId
	}
	return ""
}

func (m *RoomOperator) GetServerMsgId() string {
	if m != nil {
		return m.ServerMsgId
	}
	return ""
}

func (m *RoomOperator) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RoomOperator) GetExtend() string {
	if m != nil {
		return m.Extend
	}
	return ""
}

func (m *RoomOperator) GetOtherId() []int64 {
	if m != nil {
		return m.OtherId
	}
	return nil
}

func init() {
	proto.RegisterType((*RoomMsg)(nil), "im.app.roomMsg")
	proto.RegisterType((*RoomAck)(nil), "im.app.roomAck")
	proto.RegisterType((*RoomDeliverAck)(nil), "im.app.roomDeliverAck")
	proto.RegisterType((*RoomOperator)(nil), "im.app.roomOperator")
}

func init() { proto.RegisterFile("im.room.proto", fileDescriptor_e54fd61032f5bb56) }

var fileDescriptor_e54fd61032f5bb56 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0xba, 0x4d, 0x5a, 0xb7, 0x30, 0x64, 0xa8, 0x2c, 0xc4, 0x60, 0x65, 0xca, 0xd4,
	0x85, 0x27, 0x40, 0x65, 0xe9, 0x50, 0x21, 0x45, 0xe2, 0x01, 0xd2, 0xe4, 0x28, 0x16, 0x4d, 0x6c,
	0x9d, 0xdd, 0x8a, 0x3e, 0x18, 0xe2, 0x3d, 0x78, 0x22, 0x64, 0x3b, 0x6d, 0x43, 0x01, 0x21, 0x31,
	0xb1, 0xe5, 0x3b, 0xdf, 0xef, 0xfb, 0xef, 0x4f, 0xc2, 0x2e, 0x64, 0x3d, 0x43, 0xa5, 0xea, 0x99,
	0x46, 0x65, 0x55, 0x12, 0xc9, 0x7a, 0x56, 0x68, 0x9d, 0xbe, 0xf5, 0x58, 0xec, 0xca, 0x4b, 0xb3,
	0x4e, 0xa6, 0x2c, 0x72, 0x8f, 0x8b, 0x8a, 0x13, 0x41, 0x32, 0x9a, 0xb7, 0x94, 0x5c, 0xb1, 0xa1,
	0x46, 0xa9, 0x50, 0xda, 0x3d, 0xef, 0x09, 0x92, 0x0d, 0xf2, 0x23, 0x3b, 0xcd, 0x23, 0x7a, 0x0d,
	0x0d, 0x9a, 0x40, 0x89, 0x60, 0xe3, 0x72, 0x23, 0xa1, 0xb1, 0x4b, 0xb3, 0x5e, 0x54, 0xbc, 0x2f,
	0x48, 0x36, 0xca, 0xbb, 0x25, 0xd7, 0x61, 0x00, 0x77, 0x80, 0xa1, 0x63, 0x10, 0x3a, 0x3a, 0xa5,
	0x84, 0xb3, 0x18, 0x9a, 0x12, 0xf7, 0xda, 0xf2, 0xc8, 0x8f, 0x3d, 0xa0, 0x3b, 0x29, 0x55, 0x63,
	0xa1, 0xb1, 0x3c, 0x16, 0x24, 0x9b, 0xe4, 0x07, 0x4c, 0xae, 0xd9, 0xc8, 0xca, 0x1a, 0x8c, 0x2d,
	0x6a, 0xcd, 0x87, 0xde, 0xd2, 0xa9, 0xe0, 0x74, 0x85, 0x9d, 0xab, 0x6d, 0x63, 0xf9, 0x28, 0xdc,
	0xd8, 0x62, 0x38, 0x79, 0x30, 0x80, 0x86, 0x33, 0x41, 0x33, 0x9a, 0x1f, 0xd0, 0x6d, 0x08, 0x2f,
	0x16, 0x9a, 0x8a, 0x8f, 0xfd, 0xa8, 0x96, 0xd2, 0x57, 0x12, 0x92, 0xbb, 0x2d, 0x9f, 0x7f, 0x4c,
	0x6e, 0xca, 0xa2, 0xad, 0x01, 0x5c, 0x54, 0x3e, 0x37, 0x9a, 0xb7, 0x74, 0x9e, 0x0e, 0xfd, 0x35,
	0x9d, 0xfe, 0xd7, 0x74, 0x3e, 0x6d, 0x3a, 0xf8, 0x66, 0x53, 0x40, 0x9c, 0xab, 0x0a, 0x8e, 0xd9,
	0x05, 0x4c, 0x57, 0xec, 0xd2, 0xb9, 0xbb, 0x83, 0x8d, 0xdc, 0x01, 0xfe, 0xd1, 0x7d, 0xd7, 0x1b,
	0x15, 0xf4, 0xcc, 0x5b, 0xfa, 0x4e, 0xd8, 0xc4, 0x5d, 0x72, 0xaf, 0x01, 0x0b, 0xab, 0xf0, 0x1f,
	0x06, 0x74, 0x7a, 0xad, 0x91, 0x97, 0xb6, 0xe4, 0x82, 0x53, 0xf6, 0xc9, 0x5b, 0x8a, 0xc3, 0x87,
	0xd0, 0xe2, 0x2a, 0xf2, 0x7f, 0xce, 0xcd, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x7d, 0x34,
	0xac, 0x4a, 0x03, 0x00, 0x00,
}
